### ISSUE TITLE
Assertion: Bundle only contains bitcode-marker 

### ISSUE THREAD

**Issue by fjtrujy** [paypal/paypalcheckout-ios#1]
Using Xcode Server and the option "Universal app with thinned variants".

```
Assertion: Bundle only contains bitcode-marker /var/folders/7h/8c8nj1jd00n460jkyh3tlxlw0000gn/T/IDEDistributionThinningStep.2XL/Payload…" UserInfo={NSLocalizedDescription=Failed to verify bitcode in NativeCheckout.framework/NativeCheckout:
File: (null):(null)
```

This option is very important for us because is decreasing a lot the binary file size.

Wishing responses.

**Comment by dmikey** [comment]
Thank's for reaching out! We're quickly and rabidly moving to our next big supported release for iOS. We will ensure there is an Option that will contain Bitcode for thinned variants. Thank you for reaching out!

**Comment by dmikey** [comment]
Feel free to subscribe to our google group, for announcements https://groups.google.com/forum/#!forum/paypalcheckout

**Comment by fjtrujy** [comment]
So, first of all are you telling me that you were going to fix it, and now you have closed the issue and then added the label `wontfix`, does it means that is not going to be fixed never?

Thanks in advance

**Comment by dmikey** [comment]
Nope it's going to be fixed, I'm just marking it this as a wont fix for now, as our current release plans to ensure this isn't an issue forward.

**Comment by fjtrujy** [comment]
Hello,

Sorry to type here again, but now is even worse. 
We are trying to generate binaries in our CI system, it is: Xcode 9 + Bots configuration. Compiling with the iOS 11 SKD and there is no way to generate binaries.

If we enable the "Thinned variants" it shows exactly the same error than before.
If we disable the "Thinned variants" it shows `xcodebuild exited with status 11`.

So right now, we are forced to disable Paypal from our app if we wanna make it work.

Wishing your fast response,
Francisco Javier.

**Comment by CRoig** [comment]
Hi, any update on this?

**Comment by dmikey** [comment]
Hi @CRoig we're expecting General Availability by March of this year. I'll work with BetVictor's Sales Engineers to ensure you get notified and support as soon as we're ready to roll with our "best in class" SDKs. We're making a slew of changes that will greatly increase build compatibility.

**Comment by fjtrujy** [comment]
Hello,
We are already on March and I'm still suffering this issue.
It is a blocker for us because is totally breaking our CI/CD system!

Do you have an update overhere?
Thanks

**Comment by dmikey** [comment]
Hey @fjtrujy we will be announcing iOS soon, it's currently finishing some of the final paces with our EMEA integration engineers, and should be landing soon! Thanks so much for checking back in with us.

**Comment by xzenon** [comment]
Hi, any update on this?
