### ISSUE TITLE
[🐞] Code=-15 "Nonce mismatch" PayPal fall back error

### ISSUE THREAD

**Issue by quintonpryce** [paypal/paypalcheckout-ios#102]
### 🐞 Describe the Bug
Each time we call to the Checkout.start we get the following error only when the web fallback happens.

Domain=org.openid.appauth.general Code=-15 "Nonce mismatch" UserInfo={NSLocalizedDescription=Nonce mismatch} - Error

The Checkout.onError callback doc says that any error received cannot be recovered from which is not the case as the checkout flow does not dismiss. This error callback is causing our flow to dismiss our deposit flow even though the PayPal Checkout flow is still open.

This is causing a production level outage for our deposits.

The issue started at 6:29 pm PST today (April 27th). 

### 🌍 Environment

- iOS version: - 15.4
- SDK version (`Checkout.version`): - 0.88 & 0.84

**Comment by quintonpryce** [comment]
errorInfo.correlationIDs.sessionIDs.sdkSessionID
"44F697B9-93B5-4988-A28D-2BF35B2E9158"
errorInfo.correlationIDs.sessionIDs.orderSessionID
 "E56152B1-A06A-49CE-AFA7-509374600ED0"
errorInfo.correlationIDs.updateClientConfigDebugID
  - some : "afb387f993f75"

**Comment by jonathajones** [comment]
Hi Quinton - Investigating. Thanks for bring to our attention. We'll have an update for you tomorrow.

**Comment by jonathajones** [comment]
@quintonpryce We've identified the issue, resolution is in progress and will not require an SDK update. 
The point about non fatal errors is well taken - we'll discuss how to resolve that internally.

**Comment by quintonpryce** [comment]
Thank you for the urgency on this @jonathajones. We appreciate the team's attention on this.

Sometime in the next month or so I'd be happy to setup a time for a call to chat about the frequency of the web fallback which we see in quite a high frequency from our users. If only to add additional debug steps into our checkout to gather more data for you - we would be happy to do anything we can to help your team as we have a decently high checkout volume to work with.

**Comment by jonathajones** [comment]
Happy to help @quintonpryce ! Thanks for the prompt issue report, it was very helpful to us to understand what had gone sideways. We'll let you know about a time for us to connect to discuss the web fallback issue if needed.  Do you have location data for users that experience the web fallback, and are those users having to log in again once the webview opens?
