### ISSUE TITLE
[🐞] Stuck at "Pulling up your digital wallet" screen

### ISSUE THREAD

**Issue by kakopappa** [paypal/paypalcheckout-ios#103]
### 🐞 Describe the Bug
Stuck at "Pulling up your digital wallet" screen after login

### 🔬 Minimal Reproduction
1. Agree to "PayPal.com" to sign in
2. Login to PayPal account
3.Stuck at  "Pulling up your digital wallet" screen

### 🤔 Expected Behavior
1. Agree to "PayPal.com" to sign in. 
2. Login
3. Make the Payment

### 🌍 Environment

- iOS version: 15.2
- SDK version (`Checkout.version`): - 0.84.0, 0.88.0, 0.79.0
- Xcode 13.3.1 

### ➕ Additional Context
Add any other context about the problem here. Screenshots or videos that show the issue are very helpful.

Location permission has been granted. (While Using)
![IMG_5359FA08EABD-1](https://user-images.githubusercontent.com/7474406/166670574-dc4163b6-571d-44a4-a2ff-bf7918307b9e.jpeg)

**Comment by jonathajones** [comment]
Hi @kakopappa  - 
You'll likely need to modify your return Url set in the paypal developer portal. We've found that one of our backend authentication services doesn't handle return URLs with special characters or capital letters - so I'd suggest formatting the return URL to remove these. There won't be any impact to your payments or to the performance of the SDK with a different `returnUrl` - as long as the URIs match between what is set in the developer portal and what is used to configure the SDK. 

In a near future release, we'll be deprecating the need to provide the `returnUrl` entirely.
