### ISSUE TITLE
[🐞] Non-US addresses are required to select a US state.

### ISSUE THREAD

**Issue by rokaspoq** [paypal/paypalcheckout-ios#104]
### 🐞 Describe the Bug
When I try to add a Non-US address I'm still asked to put a US state.

### 🔬 Minimal Reproduction
Go to `+ Add an address` in `Choose a shipping address` screen and try to add a Non-US address.

### 😕 Actual Behavior
US State field is mandatory

### 🤔 Expected Behavior
US State field should not appear at all.

### 🌍 Environment

- iOS version: - 15.5
- SDK version (`Checkout.version`): - 0.88.0

### ➕ Additional Context
![Simulator Screen Shot - iPhone 13 Pro Max - 2022-05-24 at 12 34 48](https://user-images.githubusercontent.com/40168471/170026450-72ca884f-5894-4cc2-b2d3-5bbbfa03b5de.png)

**Comment by rokaspoq** [comment]
@minhthenguyen it does happen always

**Comment by minhthenguyen** [comment]
Closing this as this has been fixed in version 0.100.0.
Please open a new issue if you see the bug still persists. Thanks.
