### ISSUE TITLE
Invalid Scope 

### ISSUE THREAD

**Issue by iftikharokz** [paypal/paypalcheckout-ios#105]
This action isn't supported ( invalid scope)
  i am integrating paypalcheckout sdk in my app but getting the error when click on  PayPalButton()
![qXdcY](https://user-images.githubusercontent.com/73760345/174565482-ee719a7f-d866-428c-9ce5-4402c7245c50.png)

## Code 

```
func configurePayPalCheckout() {
           Checkout.setCreateOrderCallback { createOrderAction in
               let amount = PurchaseUnit.Amount(currencyCode: .usd, value: "10.00")
               let purchaseUnit = PurchaseUnit(amount: amount)
               let order = OrderRequest(intent: .capture, purchaseUnits: [purchaseUnit])

               createOrderAction.create(order: order)
           }

           Checkout.setOnApproveCallback { approval in
                approval.actions.capture { (response, error) in
                   print("Order successfully captured: \(response?.data)")
                    print("error :",error)
               }
           }
            Checkout.setOnCancelCallback {
                // User has cancelled the payment experience
                print("cancel")
            }
            Checkout.setOnErrorCallback { error in
                // Handle the error generated by the SDK
                print("error" , error)
            }
```
## Converting PayPalButton() to swiftui
```
struct PayPalButtonStart:  UIViewRepresentable{
    func makeUIView(context: Context) -> some UIView {
          PayPalButton()

    }
    func updateUIView(_ uiView: UIViewType, context: Context) {
        
    }
}
```
## Config  when app launches

```
init(){
        let config = CheckoutConfig(
               clientID: "AeOy-dFoyG9HiKPlYmLX8Qpzh9_xBgFUt8cl773ZfzWvaNkJuxigX06_kFsr9MaXQi2O8Bh9U31_jpHB",
               returnUrl: "theappmedia.TShirt://paypalpay",
               environment: .sandbox
           )

           Checkout.set(config: config)
    }

```

 i search on google , stackOverflow , but didn't get any solution
## Result in terminal
022-06-20 14:23:25.653584+0500 T_Shirt[14592:4424777] Random String = 9223372040329625407
2022-06-20 14:23:25.653732+0500 T_Shirt[14592:4424777] Base 64 Encoded random Number = OTIyMzM3MjA0MDMyOTYyNTQwNw==
2022-06-20 14:23:25.653771+0500 T_Shirt[14592:4424777] Nonce = 2022-06-20T09:23:25ZOTIyMzM3MjA0MDMyOTYyNTQwNw==
2022-06-20 14:23:25.700528+0500 T_Shirt[14592:4424777] :::::Signature=====MEYCIQDr6c5qglHs2E9W4UyQpAWmhFPWl74Ie6DqloSfkUTBKwIhAJFDJKyezqi2HKRfuhGZTdFVcVgENjDO/xRq6gq5w0+g
2022-06-20 14:23:25.700806+0500 T_Shirt[14592:4424777] :::::Nonce=2022-06-20T09:23:25ZOTIyMzM3MjA0MDMyOTYyNTQwNw==
2022-06-20 14:23:25.700974+0500 T_Shirt[14592:4424777] :::::Signature=MEYCIQDr6c5qglHs2E9W4UyQpAWmhFPWl74Ie6DqloSfkUTBKwIhAJFDJKyezqi2HKRfuhGZTdFVcVgENjDO/xRq6gq5w0+g
2022-06-20 14:23:25.701126+0500 T_Shirt[14592:4424777] :::::PublicKey=MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEqvpNN9EbnLhMlFP7Tk/SVZmItinVlV+QrmRA6DPeFBOq9JwNI3JDImMfJrWI64TsjElApnY4dSi7lclG2gAxrA==

**Comment by jonathajones** [comment]
Hi @iftikharokz - The issue was scope related - you should be able to navigate to the developer dashboard and enable the required scope by selecting "Native Checkout SDK". I also suggest you update to the latest version of the SDK, as you'll be able to remove the `returnURL` parameter entirely. 

<img width="562" alt="image" src="https://user-images.githubusercontent.com/74559931/176018509-bac77901-e6c7-4ec4-8d0a-ba7d642a317a.png">

Closing the issue, since it has been fixed.
