### ISSUE TITLE
[🐞] Always got invalid scope error

### ISSUE THREAD

**Issue by hungnguyen1791** [paypal/paypalcheckout-ios#107]
### 🐞 Describe the Bug
Hi,

We are follow this doc https://developer.paypal.com/limited-release/paypal-mobile-checkout/ios/ to setup paypal checkout in our iOS app. We already done all step including "Enable SDK"

But we always got "invalid scrope" error but not sure what is the root cause, please help to check.

### 🔬 Minimal Reproduction
Describe steps to reproduce. 

### 😕 Actual Behavior
A clear and concise description of what is happening. Please debugger logs and error messages if applicable.

### 🌍 Environment

- iOS version: - iOS 15.4
- SDK version (`Checkout.version`): - PayPalCheckout (0.101.0)

### ➕ Additional Context
Add any other context about the problem here. Screenshots or videos that show the issue are very helpful.
![IMG_4539](https://user-images.githubusercontent.com/91858465/184473456-52050caf-ca6e-4d06-820f-3f08d1176536.PNG)

**Comment by hungnguyen1791** [comment]
this is our client-id: AX5AB8ne4WCvhwQwU0R1aw1Y5668lP1-slbCVgxm0W2k0_XEI3PB-uh8Dv7iOQcqsHpWGk7XL8QBS-rn

**Comment by jonathajones** [comment]
Hi @hungnguyen1791 - Looks like your ClientID is missing the default permission to use Native Checkout. 

This can be enabled in your developer portal for your REST application, by opening 'Advanced Options' under 'Accept Payments' and making sure 'Native Checkout SDK' is selected:

<img width="556" alt="image" src="https://user-images.githubusercontent.com/74559931/184666870-694d75ec-de4d-4307-88da-7a932d002a3b.png">

Note that all of the account configurations will need to be applied to both your sandbox and live applications.

**Comment by hungnguyen1791** [comment]
Thanks @jonathajones 

It works fine after updating.
