### ISSUE TITLE
Logging out of Paypal Checkout Session

### ISSUE THREAD

**Issue by allenmunderdog** [paypal/paypalcheckout-ios#110]
Is there a way to programmatically log out of the current Checkout session?

The issue we are seeing is when a user logs into Paypal Checkout, their session persists even if that user logs out and then a new user logs into the app. We want to programmatically log them out of PayPal Checkout or remove the session when a user logs out of our app.

Example:

Step 0: Initial state 
     App User: nil
     Paypal User: nil

Step 1: User A logs into the app
     App User: A
     Paypal User: nil

Step 2: User A logs into their Paypal Checkout
     App User: A
     Paypal User: A

Step 3: User A logs out of the app
     App User: nil
     Paypal User: A

Step 4: User B logs into the app
     App User: B
     Paypal User: A

Step 5: User B goes to Paypal checkout and is able to use User A's Paypal.
     App User: B
     Paypal User: A
     
When the user logs out of the app (Step 3) we want to ensure the Paypal Checkout session is also logged out to prevent this from happening.

We implemented the sdk based on: https://developer.paypal.com/limited-release/paypal-mobile-checkout/ios/programmatically-start-sdk/

**Comment by jonathajones** [comment]
Hi @allenmunderdog - This is a great suggestion and I've passed it along to our product team. We're prioritizing it and I'll reply here when we have an ETA for the feature. 

Thank you!

**Comment by ryantallmadge** [comment]
###

**Comment by susietucker** [comment]
+1

**Comment by developer-dmp** [comment]
+1

Also looks like this was brought up on the Android side as well. Would be amazing if these could be looked at together: https://github.com/paypal/android-checkout-sdk/issues/99

**Comment by editorabruno** [comment]
+1

**Comment by jonathajones** [comment]
> +1
> 
> Also looks like this was brought up on the Android side as well. Would be amazing if these could be looked at together: [paypal/android-checkout-sdk#99](https://github.com/paypal/android-checkout-sdk/issues/99)

This is the idea :) 
We are still determining the roadmap, but this will be included in a near term release, so you'll see this sooner than later.

**Comment by ryantallmadge** [comment]
Hello all, Wondering if there has been any updates on this?

**Comment by jonathajones** [comment]
Hi @ryantallmadge - Yep, support for this is in progress. It'll be included in one of the next two releases, depending on how long it takes to complete.

**Comment by jonathajones** [comment]
@ryantallmadge This should now be supported via the following interface `Checkout.logoutUser()` as of  version `0.110.0`
