### ISSUE TITLE
[🐞] onShippingChageCallBack not working

### ISSUE THREAD

**Issue by mpalanisamy-pkglobal** [paypal/paypalcheckout-ios#111]
### 🐞 Describe the Bug
onShippingChageCallBack is not working when programmatically starting the SDK

### 🔬 Minimal Reproduction
configure the SDK and start the checkout order creation is happening but onShippingChange call back is not returning while changing the shipping address.

### 😕 Actual Behavior
 when starting the SDK programmatically and creating the checkout order with the order request start, onCancel, onError callbacks are working but the **onShippingChange** callback is not working for the first time creating the order as well changing the shipping address/shipping option from the SDK sheet.
Getting **On Shipping Change Not Set** message from the onError callback when changing the shipping option from the SDK UI.

### 🤔 Expected Behavior
**onShippingChange** callback should work in the first time start with the order creation and subsequent change in the address change in the SDK sheet UI.

### 🌍 Environment
sandbox
- iOS version: 15.5
- SDK version (`Checkout.version`): - 0.106.0 latest(SPM)

### ➕ Additional Context
Please confirm any configuration need for the onShippingChange callback

**Comment by minhthenguyen** [comment]
@mpalanisamy-pkglobal Thank you for reporting the issue.
Just to clarify, did it happen when you set the callback with `Checkout.start(onShippingChange: ...)`?

**Comment by mpalanisamy-pkglobal** [comment]
yes @minhthenguyen

**Comment by minhthenguyen** [comment]
Got it, this bug has been fixed internally and will go in our next release.

For now, would you be able to try using the callback setter inside `CheckoutConfig.init(onShippingChange: ...)`, or use `Checkout.setOnShippingChangeCallback()` function?
Sorry for the inconvenience, I'll also keep you posted inside this thread on when we do the next release with the fix.

**Comment by jonathajones** [comment]
Hi @mpalanisamy-pkglobal  - This is resolved in the latest release (in `0.109.0`)
