### ISSUE TITLE
[🐞] Got invalid scope error

### ISSUE THREAD

**Issue by hungnguyen1791** [paypal/paypalcheckout-ios#112]
### 🐞 Describe the Bug

I got this issue on the sandbox environment (https://github.com/paypal/paypalcheckout-ios/issues/107), with your help the issue is resolved. We can do the payment with Paypal successfully on sandbox now.

But with the same configuration for live applications, We still face this issue.

our client-id is: Aerfm2r9KtDofw6kosyj_mwyq8MdBouDGnxs_ODluW3878kDpB-Un12M6uSHpuW8M-5aD96mAklEsxQA

we already set live environment in code:
let config = CheckoutConfig(clientID: paypalClientId,
                                        environment: Environment.live)
Checkout.set(config: config)

please help us on this issue, Thanks

### 🔬 Minimal Reproduction
Describe steps to reproduce. 

### 😕 Actual Behavior
A clear and concise description of what is happening. Please debugger logs and error messages if applicable.

### 🌍 Environment

iOS version: - iOS 15.4
SDK version (Checkout.version): - PayPalCheckout (0.101.0)

### ➕ Additional Context
Add any other context about the problem here. Screenshots or videos that show the issue are very helpful.
![image](https://user-images.githubusercontent.com/91858465/193197944-76cc3221-f027-4ae9-8238-84ea9e3066a8.png)

**Comment by jonathajones** [comment]
Hi @hungnguyen1791 - 
Looked into this, and your client ID does not have the 'Full Name' or 'Email' permissions associated with it (see https://developer.paypal.com/limited-release/paypal-mobile-checkout/ios/#link-enablethesdk) 

To enable these options, make sure the following boxes are checked in the settings of your rest app in the developer portal: 

<img width="435" alt="image" src="https://user-images.githubusercontent.com/74559931/193320039-5e17defb-48ba-45b9-8c0e-4ef253eb2833.png">


Let me know if this resolves the issue for you. 
Thanks!

**Comment by hungnguyen1791** [comment]
Thanks @jonathajones ,

we just updated the configuration based on your suggestion. How long does it take to review? and How can we know the review process is done to start testing?

Thanks.

**Comment by jonathajones** [comment]
Hi @hungnguyen1791  - 
The requirements to add the `fullName` and `email` permissions have actually been removed in a more recent version of the SDK, so this is not a category of issue you should see going forward. We still need to enable the `Login with PayPal`, but the review time won't be necessary since you won't be enabling the `Full Name` or `Email` checkboxes
