### ISSUE TITLE
how to test not native eligible use case

### ISSUE THREAD

**Issue by nerocristallo** [paypal/paypalcheckout-ios#113]
How can I test the web fallback for not native eligible use case?

In Android SDK it can be done setting true the shouldFailEligibility in SettingsConfig but I am not able to find anything similar in iOS sdk.

**Comment by jonathajones** [comment]
Hi @nerocristallo - Sorry for the delay responding to this, and thank you for reporting the issue. We're working to align the codebases internally, and should have better parity in our upcoming GA release.

**Comment by jonathajones** [comment]
Hi @nerocristallo - 
This was released in version `0.112.0` : 
> Added the ability to force a web fallback
>     Can be seen via setting yourCheckoutConfig.showWebCheckout = true
