### ISSUE TITLE
[🐞] Crash when uesr checkout on iOS 12.x(or early version)

### ISSUE THREAD

**Issue by whtoo** [paypal/paypalcheckout-ios#114]
### 🐞 Describe the Bug

You can use our app called `Aosom` which you can search 'Aosom' on App Store.

When our app upgrade SDK within 0.108.0, we found many wired crash caused by paypal on firebase logs.

### 🔬 Minimal Reproduction

When customer begin checkout  and choose paypal to checkout in iOS 12.x.

They will get crash.

### 😕 Actual Behavior
User who use iOS 12.x or early would get crash using paypal to checkout on our app.

### 🤔 Expected Behavior

User who use iOS 12.x or early can successfully checkout.

### 🌍 Environment

- iOS version: - 12.x or early
- SDK version (`Checkout.version`): - 0.108

### ➕ Additional Context
The firebase log as below.
![截屏2022-10-11 13 53 04](https://user-images.githubusercontent.com/909131/195007404-44f3f90e-b3a1-4638-8d68-964903ff8992.png)

**Comment by jonathajones** [comment]
Hi @whtoo  - 
Thanks for submitting the issue. Could you give us a bit more information about the issue? A raw stack trace / section of a crash report may be helpful. 

Also - is yours an objective-c integration, or a swift integration?

Thanks,
Jon

**Comment by whtoo** [comment]
Hi @jonathajones -

Thanks for your reply.

We use paypal in swift integration.

And we manage crash report with firebase, so raw stack trace that is hard to submit.

But I guess `connectedScenes` will be key term. 
I search it in our codes and got no calling or definition.
And it is on top of every crash report associated with paypal.

I know paypal SDK is working on iOS 11+, but this api should be 13+.

Perhaps checking warnning api calling is a good clue for this case.

Thanks,
whtoo

**Comment by jonathajones** [comment]
Hi @whtoo  - Thanks for the context - I believe we've found the issue and we'll work to resolve it for our next release

**Comment by whtoo** [comment]
@jonathajones - Thanks for your reply, could you kindly tell us when to fix it ? ( We need a exactly time to reply to our customer who face it)
It exists for so much long time yet.

**Comment by whtoo** [comment]
@jonathajones 
crash still exist on 0.110.0 !!! 
Please help us to fix it ! 
It's a critical issue.

**Comment by whtoo** [comment]
@jonathajones

**Comment by ndilworth** [comment]
Hi @whtoo we are seeing a similar issue on iOS 12, was there a change you made to resolve your issue?

**Comment by whtoo** [comment]
> Hi @whtoo we are seeing a similar issue on iOS 12, was there a change you made to resolve your issue?

Sorry, I have no idea about solution to this issue. 😭
If iOS 12 users are a small percentage of your customer base,
 perhaps filtering Paypal directly is a downgrade option.
