### ISSUE TITLE
[🐞] Xcode 14 SwiftUI Preview crashes when PayPalCheckout is present

### ISSUE THREAD

**Issue by quintonpryce** [paypal/paypalcheckout-ios#115]
### 🐞 Describe the Bug
I have tried the most recent release (0.109) & having PayPalCheckout sdk added to my project crashes all SwiftUI Previews.

```
HumanReadableSwiftError

SettingsError: noExecutablePath(<IDESwiftPackageStaticLibraryProductBuildable:ObjectIdentifier(0x00006000c07855c0):'PayPalCheckout'>)
```

### 🔬 Minimal Reproduction
Using Xcode 14, add PayPalCheckout SDK to a project that has SwiftUI views with Swift Package Manager.

Try & preview a SwiftUI View.

_I have a UIKit project with swiftui subviews._

### 🌍 Environment

- iOS version: - 16.0, 15.5
- SDK version (`Checkout.version`): - 0.109

**Comment by quintonpryce** [comment]
https://developer.apple.com/forums/thread/707569?page=5

Seems another project was having a similar issue & I believe they have since fixed it.

**Comment by quintonpryce** [comment]
https://github.com/microsoft/appcenter-sdk-apple/pull/2433

It was AppCenter. They have a branch with a fix on it.

**Comment by jonathajones** [comment]
@quintonpryce Thanks for opening this - we will triage and update here when we've identified a resolution.

**Comment by quintonpryce** [comment]
Thanks @jonathajones, I'm having to remove the SDK from my app in order to do any UI building.

**Comment by jonathajones** [comment]
Investigation is in progress - sorry for the headache @quintonpryce !

**Comment by jonathajones** [comment]
Hi @quintonpryce - We did some investigation on this, and these are our findings: 

We created a new swiftUI project, added the SDK as a package dependency and tested preview for content views on various xcode versions:

xcode 14.0 -> works as you described
xcode 14.1 beta 3 -> works as expected
xcode 14.1 rc (released today) -> works as expected

Could you try with the RC and verify our findings?

**Comment by quintonpryce** [comment]
Yes the release candidate seems to have fixed the issue. I'm sorry to have wasted your teams time on this! Cheers.

**Comment by jonathajones** [comment]
No problem at all, happy to help 👍
