### ISSUE TITLE
📙 PayPalButton Deprecated - Validate user input before entering PayPal Checkout

### ISSUE THREAD

**Issue by garethlloyd94** [paypal/paypalcheckout-ios#116]
### 📙 Describe the Issue
When tapping on the PayPal button, we have a form, which we need to validate the input before opening the PayPal native checkout. Previously I had this working using the PayPalButton, and adding a target to the button and opening the SDK manually, however this has been deprecated in favour of PaymentButtonContainer. And there doesn't seem to be a way to add a target to this.

I have tried a few different things, including canceling the action in the create order callback, however this causes the native checkout to pop up and dismiss immediately. 

The previous method of using the deprecated button also doesn't work, as this button now triggers the checkout to start when previously it didn't

### 😕 Actual Behavior
Tapping button automatically opens the PayPal checkout

### 🤔 Expected Behavior
Tapping button runs the validation, and then PayPal native checkout is opened programatically

**Comment by jonathajones** [comment]
Hi @garethlloyd94 - 
Thanks for the feedback! 
It looks like you're looking for some opportunity to change the behavior of the payment button so it does not start until you have completed your validation. Is that right? We will look into adding this functionality in the future. You have a couple options before then, however - 

1. You could create your own PayPal button and programmatically start the SDK at the time of your choosing after your validation is complete.
2. As a stopgap - you may be able to achieve the behavior you're looking for by first calling 
`.removeTarget(nil, action: nil, for: .touchUpInside)` on the `PayPalButton` - but this is not officially supported behavior and you would be responsible for starting the sdk via `Checkout.start` on your own. This API is also liable to change as we continue to refine how the buttons should behave, and the `PayPalButton` itself may be removed from the public interface in the future.

Thanks! 
Jon

**Comment by garethlloyd94** [comment]
Thanks @jonathajones for getting back so quickly, I'll need to go with option 1 for just now. Thanks for your help
