### ISSUE TITLE
📙 Deprecation and documentation issues for 0.109.0

### ISSUE THREAD

**Issue by joshuapoq** [paypal/paypalcheckout-ios#118]
### 📙 Issues
1. `0.109.0` breaks SPM semantic versioning requirements; for example `ShippingChangeAddress/init` has been removed and replaced rather than deprecated with rename.
1. The initialiser parameter order is now reversed and this is confusing when there is no documentation.
1. The new address fields should be documented to match your [API docs which were the only useful resource](https://developer.paypal.com/docs/api/payments/v2/).
1. The deprecations on `ShippingChangeAddress` should be the exact new values.
   1. `state` should be deprecated as `renamed: "adminArea1"`.
   1. `city` should be deprecated as `renamed: "adminArea2"`.

**Comment by jonathajones** [comment]
Hi @joshuapoq - Apologies for this, and thanks for letting us know. We're in the process of preparing for promotion to `1.0.0`, and part of this work involves updating several of our public facing types. You're right to point out that this should be documented and deprecated - rather than fully removed; we'll add documentation for this and a better migration path in our next version.

**Comment by jonathajones** [comment]
@joshuapoq We are re-adding the removed values, and adding deprecation messages and documentation to the values we're exposing. This won't necessarily help users of `0.109.0`, but I'm hoping that it can ease the transition of users on `0.109.0` to `0.11x.0` 

Thanks again for letting us know about this!

**Comment by joshuapoq** [comment]
That's no problem! I didn't want to raise this as a bug and I know the push towards full releases especially with docs! Thanks for the response.

**Comment by joshuapoq** [comment]
Hi @jonathajones - bit of a follow up on this. We've had more breaking issues from `0.111.0`. Can you confirm that from 1.0 PayPal will be correctly following semantic versioning for SPM?

**Comment by jonathajones** [comment]
Hi @joshuapoq  - Yes, we will be following semantic versioning once we go to `1.0.0`. Until then, we'll call out breaking changes on the releases and in the changefile (ie https://github.com/paypal/paypalcheckout-ios/releases/tag/0.112.0)
