### ISSUE TITLE
[🐞] Payment process stuck at redirecting the user after login

### ISSUE THREAD

**Issue by ilendemli** [paypal/paypalcheckout-ios#121]
### 🐞 Describe the Bug
One of our clients complained about users not being able to pay using PayPal. For some reason the callback to the app after login and approval does not happen. It's an app with shared code-base and other clients do not have such issue.

### 🔬 Minimal Reproduction
Select payment method, login with credentials, PayPal says "redirecting", but nothing happens.

### 🤔 Expected Behavior
Redirect happening without issues

### 🌍 Environment

- iOS version: 15.5 and 16.0
- SDK version: 0.28.0 and 0.109.0

The only hint I get in the console is it printing `[AXRuntimeCommon] Unknown client: VVT`

<img src="https://user-images.githubusercontent.com/2271750/202003369-9b6a4ac3-c565-47dc-a7b9-2b8e067359b4.png" width="256">

https://user-images.githubusercontent.com/2271750/202003393-ce81c404-0943-4c3e-bfed-d9923bc28883.mov

**Comment by devchristina** [comment]
@ilendemli Is this still an issue? If no response is received by 10/27 we will close this issue as not planned.
