### ISSUE TITLE
[🐞] Crash After Checkout.createOrder callback

### ISSUE THREAD

**Issue by quintonpryce** [paypal/paypalcheckout-ios#125]
### 🐞 Describe the Bug

I have tested the flow and do not crash so I can't be certain where the crash is coming from but I know from my logs that the `createOrder` api callback is always called before it crashes.

I've included the little information in the logs to hopefully draw some lines to your own obfuscation of the crash from your side.

```
Fatal Exception: NSInternalInconsistencyException
attempt to insert row 1 into section 0, but there are only 1 rows in section 0 after the update

keyboard_arrow_up
0
CoreFoundation
__exceptionPreprocess
1arrow_drop_down
libobjc.A.dylib
objc_exception_throw
arrow_right 2
Foundation
_userInfoForFileAndLine
```

### 🌍 Environment

- iOS version: - 15 & 16
- SDK version (`Checkout.version`): - 0.109

**Comment by quintonpryce** [comment]
This is the #1 crash in our app of 200k+ users, accounting for ~0.5% of crashed users. Please let me know if there is anything I can do to help debug this one 🙂

**Comment by jwarmkessel** [comment]
Hi @quintonpryce, we are tracking this issue now.

**Comment by jonathajones** [comment]
Hi @quintonpryce  - Apologies for the delayed response. Do you have a symbol trace of an example of the issue in your logs?

**Comment by devchristina** [comment]
@quintonpryce Is this still an issue? If no response is received by 10/27 we'll close this issue as not planned.
