### ISSUE TITLE
why payment sheet do not show text??

### ISSUE THREAD

**Issue by Oooooori** [paypal/paypalcheckout-ios#126]
### 🌍 Environment

- iOS version: 14.2
- SDK version (`Checkout.version`): 0.110.0

![IMG_4205](https://user-images.githubusercontent.com/6789482/208028472-0db9b15b-b710-4e50-8021-bd1a7bb68dfe.jpeg)
![IMG_4206](https://user-images.githubusercontent.com/6789482/208028483-a7c72e1b-6e81-40b1-b26a-326f6a0737fb.jpeg)

**Comment by vradopp** [comment]
Hi @Oooooori can you share which language the device/simulator is using where you see this issue?

**Comment by Oooooori** [comment]
@vradopp

**Comment by Oooooori** [comment]
Hi @vradopp 
language: using Chinese  and  English both have this issue
install: Cocoapods

**Comment by Oooooori** [comment]
@vradopp 
some error logs:

[assertion] Error acquiring assertion: <Error Domain=RBSAssertionErrorDomain Code=3 "Target is not running or required target entitlement is missing" UserInfo={RBSAssertionAttribute=<RBSDomainAttribute| domain:"com.apple.webkit" name:"Background" sourceEnvironment:"(null)">, NSLocalizedFailureReason=Target is not running or required target entitlement is missing}>
[ProcessSuspension] 0x12ffcc240 - ProcessAssertion: Failed to acquire RBS Background assertion 'WebProcess Background Assertion' for process with PID 22658, error: Error Domain=RBSAssertionErrorDomain Code=3 "Target is not running or required target entitlement is missing" UserInfo={RBSAssertionAttribute=<RBSDomainAttribute| domain:"com.apple.webkit" name:"Background" sourceEnvironment:"(null)">, NSLocalizedFailureReason=Target is not running or required target entitlement is missing}

**Comment by jonathajones** [comment]
HI @AhmedShanab74 - Thanks for the report. What region-language localization combination are you using? Using cocoapods, I'm able to see Arabic localizations using `0.112.1`: 

![image](https://github.com/paypal/paypalcheckout-ios/assets/74559931/428788bf-d45f-4ffd-83e5-9699a489a3cf)

**Comment by AhmedShanab74** [comment]
mobile region -> Egypt 
mobile language -> Arabic 
app language -> Arabic and English 
in Arabic language payment sheet don't show any text even i run it on simulator and make region USA
and this STARTUP_1 

![Simulator Screenshot - iPhone 14 Pro Max - 2023-05-17 at 10 58 13](https://github.com/paypal/paypalcheckout-ios/assets/128382748/95b08c40-9493-497c-8aaa-ae77633f6dce)
![Simulator Screenshot - iPhone 14 Pro Max - 2023-05-17 at 11 03 15](https://github.com/paypal/paypalcheckout-ios/assets/128382748/d172b2a9-aa6b-4171-9406-e0daf03b9cb4)

**Comment by jonathajones** [comment]
Re-opening this for now - it seems there are some localization gaps in one of our underlying dependencies.

**Comment by jonathajones** [comment]
@AhmedShanab74 When i change the region to Egypt and language to Arabic, I'm still able to get localized screens: 
![image](https://github.com/paypal/paypalcheckout-ios/assets/74559931/26883631-ec65-40ac-82db-cd03164037c7)

Can you try to reproduce this in an empty project?

**Comment by AhmedShanab74** [comment]
@jonathajones  the issue was in the Localize pod i change it and it works fine , thank u for ur help .
