### ISSUE TITLE
[🚀] Venmo & Guest Checkout Support

### ISSUE THREAD

**Issue by quintonpryce** [paypal/paypalcheckout-ios#128]
### 🚀 Feature Request

I see in the headers that there is mention of these button configurations but adding them doesn't appear to load.

I figured that your team just hasn't had time to look into yet.

**Comment by stephenhyde** [comment]
+1

**Comment by devchristina** [comment]
@quintonpryce Can you confirm that this is still an issue. If no response is received by 10/27 we will close this issue as not planned.
