### ISSUE TITLE
Checkout completed callback is never called.

### ISSUE THREAD

**Issue by martinprot** [paypal/paypalcheckout-ios#13]
Here's the way I start the native checkout.

```
	PYPLCheckout* checkout = [PYPLCheckout sharedInstance];
	checkout.delegate = self;
	self.webviewView.delegate = self;
```
in webview delegate:

```
- (BOOL)webView:(UIWebView *)webView shouldStartLoadWithRequest:(NSURLRequest *)request navigationType:(UIWebViewNavigationType)navigationType {
	[self.paypalLoader startAnimating];
	PYPLCheckout* checkout = [PYPLCheckout sharedInstance];
	return [checkout webView:webView shouldStartLoadWithRequest:request navigationType:navigationType];
}
```

When I click on the paypal button, the Safari view controller with Paypal workflow is displayed. When I pay, the Safari view controller closes, but `-(void) PayPalCheckoutCompleted: (NSDictionary*) details` is never called.

**Comment by dmikey** [comment]
Can you share the URL that is showing in SFVC during this transaction? Thanks!

**Comment by DaveCC94** [comment]
This is happening to me as well, but I'm using WKWebView. The delegate method doesn't get called, the only difference to me is that the safari browser doesn't get closed. I don't know where to go from here.

**Comment by javbar92** [comment]
???? Where is the solution to this issue?

**Comment by jonathajones** [comment]
This issue was closed, as this version of the SDK has been fully deprecated. 
The latest version of the SDK has a different architecture and doesn't have this issue. 
@javbar92 if you're seeing this issue on the latest SDK version (currently `0.51.0`), please open a new issue and describe the your experience. 

Thanks!
