### ISSUE TITLE
[🐞] Bug Report - iOS 14.x will crash on PayPal SDK when `block_destroy_helper ` is fired.

### ISSUE THREAD

**Issue by whtoo** [paypal/paypalcheckout-ios#130]
### 🐞 Describe the Bug
iOS 14
### 🔬 Minimal Reproduction
1. user select paypal method to checkout.
2. paypal sdk calling
3. user type accout info completely.
4. paypal handle transaction.
5. our server communicate with paypal server.
6. the transaction finished and crashed.
### 😕 Actual Behavior
![截屏2023-02-06 08 14 41](https://user-images.githubusercontent.com/909131/216854738-d1cf8128-5dc7-4129-9f9c-05b65a5cb29a.png)
### 🤔 Expected Behavior
No crash !!!
### 🌍 Environment

- iOS version: - 14.x
- SDK version (`Checkout.version`): - 0.110

### ➕ Additional Context
It is occasionality happening now when we upgrade SDK to 0.110, so please check the change on 0.110.

**Comment by jonathajones** [comment]
Hi @whtoo - thanks for the bug report! Do you have a sense for what percentage of traffic is affected by this crash?

**Comment by whtoo** [comment]
Hi @jonathajones - It's about 5% estimated from firebase log. But the relative percentage of our crash report is over 50%.
Please help us to fix it.It's not good for customer and us.

**Comment by whtoo** [comment]
if 5% means when 20 customers use paypal,  one of them will crash by this issue.
And relative percentage  = (paypal SDK's crash / total crash of our app)

**Comment by jonathajones** [comment]
Thanks for the context, @whtoo . Unfortunately, we are not able to pull the symbolmap files for the latest sdk version, which would be the normal next step here. 

Do you have any similar crashes for previous versions? if so, we may be able to send you the symbol map file for that version for you to use to desymbolicate the stack trace.

**Comment by whtoo** [comment]
Hi @jonathajones - Thank for your tips, according to logs, I can ensure that the crash begin from 0.110 - the least version for now.
I think we should take action maybe like generating symbol map to track the issue.
But all effective actions need your help.
Please help us to dig it and fix it.
Thx a lot.

**Comment by whtoo** [comment]
The related issues about PayPal's SDK raised from 0.110.
The picture will show all related cases within the last 30 days.
![截屏2023-02-13 08 44 36](https://user-images.githubusercontent.com/909131/218347682-000297b2-28f0-4840-8a75-051caf45c005.png)

**Comment by jonathajones** [comment]
We are currently working on our `1.0.0` release - until that is available, i recommend downgrading to the `0.109.0` release, and watching your logs. If you see occurrences of these crashes on `0.109.0`, then we would be able to provide the symbolmap files to help desymbolicate and identify exactly where the crash is happening.

**Comment by whtoo** [comment]
@jonathajones Get it. I have already followed your suggestion. Let's wait for the logs. Thanks a lot.
