### ISSUE TITLE
📙 PayLater doc is missing and we can't know how to setup it on client-side.

### ISSUE THREAD

**Issue by whtoo** [paypal/paypalcheckout-ios#131]
### 📙 Describe the Issue
Paypal-PayLater is not showing properly on our app.
And I contact with paypal server tech-supporter, but they 
don't reply my email. I need assistance that the option for 
paylater on client-side, even for server side doc if you kindly 
give me a help.
### 🔬 Minimal Reproduction
0.110

### 😕 Actual Behavior
The  DOC of `PayLater` is missing, and we don't know how to 
detect the issue paylater entrace is not showing should blame to server or client?

### 🤔 Expected Behavior
I want a doc link to guide.
The doc can clearly tell us how to setup support `paylater` on cleint-side and 
give me a hint to capture the option issue of server or merchant account.
That will be very helpful.

### ➕ Additional Context
None.

**Comment by whtoo** [comment]
@jonathajones Hi, can you kindly give me assistance? I need your help.

**Comment by whtoo** [comment]
![截屏2023-02-07 08 29 33](https://user-images.githubusercontent.com/909131/219224826-ac751c63-8b4a-4bbb-92f1-605befcbeca5.png)
@dmikey @jonathajones  Can you help me to have a look? It's my codes about `pay-later`. If you can review it, please help me.

**Comment by jonathajones** [comment]
Hi @whtoo - I don't believe that configuring an order to be Pay Later is something that needs any configuration (or is able to be configured) ahead of time. Are you looking instead to create a billing agreement? 

The Pay Later feature is one of a number of funding instruments that an end user could select. Does this help at all? I'm not sure I fully understand the request.

**Comment by whtoo** [comment]
@jonathajones - Thank you for your reply. That means that the option to show that you can use paylater depends on the merchant configuration and the risk control of the paypal server. Am I understanding this correctly?
