### ISSUE TITLE
[🐞] Bug Report

### ISSUE THREAD

**Issue by mpalanisamy-pkglobal** [paypal/paypalcheckout-ios#132]
### 🐞 Data missing in callbacks
onShippingChange callback is not sending the full address.

### 🔬 Minimal Reproduction
Initialize the SDK and continue with Checkout.start function and setOnShippingChangeCallback will be called. In the shippingChangeCallback we are not getting the user full shipping address. 

### 😕 Actual Behavior
adminArea1, AdminArea2 is providing the state and city code but AddressLine1 and AddressLine2 values are not getting.

### 🤔 Expected Behavior
Expecting adminArea3, adminArea4, fullName details 

### 🌍 Environment

- iOS version: -16.0
- SDK version (`Checkout.version`): -0.110.0

### ➕ Additional Context
from the callbacks we are not getting the required information from Paypal account
Callback: onShippingChange
AddressLine1(adminArea3), AddressLine2(adminArea4), fullName
Callback: onApproval
onApproval.cart.bill
firstname, lastname, phone

**Comment by jonathajones** [comment]
Hi @mpalanisamy-pkglobal  - 

We do not provide `addressLine1` and `addressLine2`, as it is considered protected information until the user completes the transaction with that address. We only provide`adminArea1` and `adminArea2` in the shipping callback to allow you to recalculate shipping costs based on the locality / postal code.  This should be consistent across iOS and Android with the latest release (`0.112.0`)
