### ISSUE TITLE
Where do we get PayPal user Phone Number?

### ISSUE THREAD

**Issue by mpalanisamy-pkglobal** [paypal/paypalcheckout-ios#133]
### 🚀 currently not able to get phone number from approval callback or intent success callback

A clear and concise description of what the feature is.

### Motivation

The requirement is we need to pass the Paypal user phone number

### Example

Please provide an example for how this feature would be used.

**Comment by jonathajones** [comment]
Hi @mpalanisamy-pkglobal - The SDK cannot provide comprehensive order response data in the `ApprovalData` object vended back through the approval callback. There are a few reasons for this - 
1. The SDK handles both web fallback traffice and native traffic. The data vended back to the SDK from these flows are different. 
2. The SDK supports multiple sources of tokens - for example, the SDK supports both the [orders/v2](https://developer.paypal.com/docs/api/orders/v2/) api and the [v1/payments](https://developer.paypal.com/docs/api/payments/v1/) APIs. These APIs do not provide us comprehensive and matching information around the order at the end of the SDK flow. 
 
**If you're using the orders/v2 API**, this can be done via the `actions` object vended in the approval callback: 
```swift
  ...
  onApprove: { approval in
    approval.actions.getOrderDetails { details, error in
      // details?.payer?.phone
    }
  }
```

If you need more information than is available via this action, or if you are using a different API to source your token, you can get complete buyer information associated with your order by making a `GET` request for the details of your order - the `v2/orders` endpoint [can be found here](https://developer.paypal.com/docs/api/orders/v2/#orders_get)
This is where you can find the phone number associated with the transaction.

**Comment by mpalanisamy-pkglobal** [comment]
@jonathajones , thank you for the updates. But this solution also doesn't work for me. From the details response, the phone object itself gets nil. But the same works fine in Andriod SDK with the same sandbox user account.  Please find the attached reference. Kindly validate from your end.
<img width="538" alt="Screenshot 2023-02-10 at 1 08 00 PM" src="https://user-images.githubusercontent.com/63121083/218082882-397f14ae-8b9f-4676-8e84-224738211b0c.png">

**Comment by jonathajones** [comment]
Hi @mpalanisamy-pkglobal - It is not intended to be able to get the phone number of every approve order transaction. A phone number shouldn't be relied on in the approve payment flow, since I don't think it's possible to guarantee that the order details will include a phone number. I believe the Android SDK would only be vending a masked number in the approval response - is that right?

**Comment by mpalanisamy-pkglobal** [comment]
@jonathajones , android SDK is providing the actual phone number, not a masked one. And from our business billing address should contain the phone number otherwise the order will be failed. In iOS SDK callbacks(onApprove, approval.actions.capture) we are not getting phone numbers either as phone object or as part of the billing address. I've included for you the Android response data.
**onApprove success callback phone Object**
phones=[Phone(number=**4404097084**), Phone(number=**4083698200**)]),
**onApprove success billingAddress object**
billingAddress=BillingAddress(address2=, city=San Jose, address1=1 Main St, lastName=Elango, title=, postBox=, countryCode=US, phone=, companyName=, secondName=, salutation=, postalCode=95131, stateCode=CA, firstName=Priyanga, jobTitle=, preferred=false, default=false, fullName=Priyanga Elango, addressId=027c5e5da7e118c700a910daf9, phoneNumber=**4404097084,** paymentType=null)

First Name and Last Name also we are not getting from billing address.

**Comment by jonathajones** [comment]
Hi @mpalanisamy-pkglobal - Which API are you using to generate the tokens that you pass into the checkout SDK?

**Comment by mpalanisamy-concentrix** [comment]
@jonathajones , we received a clientID from the business team and configured it in SDK initialization in the app delegate.

**Comment by jonathajones** [comment]
Not the client ID - but the token being passed into the SDK through the `createOrder` callback

**Comment by mpalanisamy-concentrix** [comment]
@jonathajones , we are doing "Checkout with payment buttons" option.

**Comment by jonathajones** [comment]
Could you copy the `createOrder` closure here so I can try to reproduce what you're seeing?

**Comment by mpalanisamy-concentrix** [comment]
@jonathajones , 
        Checkout.start(
            createOrder: { createOrderAction in
                
                let order = self.createNewOrder()
                createOrderAction.create(order: order)
                
            }, onApprove: { approval in
                
                self.paypalCheckoutOrder(approval)
            }, onCancel: {
                
                self.performCompletion(succeed: false, order: nil)
            }, onError: { error in
                
                self.errorResultAction(errorMessage: error.reason)
            }
        )

**Comment by jonathajones** [comment]
Hi @mpalanisamy-concentrix  - Enabling "Contact Telephone Number" as Stephanie described here (https://github.com/paypal/paypalcheckout-ios/issues/138#issuecomment-1468927348) is the correct way for the phone number to be vended. 

That the Android SDK was vending the full phone number was unintended, and you should see it vending the masked phone number now
