### ISSUE TITLE
[🐞] PayPal Checkout always opening web UI flow instead of native UI

### ISSUE THREAD

**Issue by mpalanisamy-concentrix** [paypal/paypalcheckout-ios#136]
### 🐞 Describe the Bug
While clicking the PayPal checkout button the SDK is always loading the web UI flow instead of the native UI.

### 🔬 Minimal Reproduction
Go to the PayPal Checkout button page and click the checkout button and now the Paypal sdk loading always the web UI. 

### 😕 Actual Behavior
After clicking the PayPal checkout button Payal SDK is loading the web UI.

### 🤔 Expected Behavior
After clicking the PayPal checkout button Paypal SDK should load the native UI.

### 🌍 Environment

- iOS version: - iPhone 13 OS 16.3
- SDK version (`Checkout.version`): - v 0.110.0

### ➕ Additional Context

https://user-images.githubusercontent.com/105424366/222430113-5bd67301-f4ae-4476-854f-9de92c76de9e.mp4

This behaviour we are facing with the specifications mentioned device. We tried to uninstall the app and restart the device multiple times but still had the same issue.

**Comment by jonathajones** [comment]
Hi @mpalanisamy-concentrix  - Could you provide us an EC token where you encountered this behavior?

**Comment by Eric-Catalyst** [comment]
Is there a way to check if the native experience is supported prior to performing a transaction? We may need to disable the PayPal option if native is not supported in the country the user is in. 

Also, how is location determined? Is it dynamic based on the current location of the device or based on the device's locale settings?

**Comment by Eric-Catalyst** [comment]
Is the EU country list pre or post Brexit?

**Comment by Eric-Catalyst** [comment]
Also, could you document this limitation in the reference documentation for the SDK? It was a bit of a surprise.

**Comment by jonathajones** [comment]
Hi @Eric-Catalyst - It's mentioned in our public docs here - https://developer.paypal.com/limited-release/paypal-mobile-checkout/#link-eligibility

The UK is a supported country as well

**Comment by Eric-Catalyst** [comment]
Right. Post Brexit the UK is not in the EU, so that is a bit out of date. I recommend you also document it here: [https://paypal.github.io/mobile-checkout-docs/ios/reference/](https://paypal.github.io/mobile-checkout-docs/ios/reference/) as that is what we spent most of our time looking at. I don't think we ever saw the limited release note.

**Comment by Eric-Catalyst** [comment]
You can close this as we now understand it is a design feature not a defect in the SDK.

**Comment by mpalanisamy-concentrix** [comment]
By Changing the Device Region to supported countries this issue is resolved
