### ISSUE TITLE
[🐞] In iPad device no keypad is poping up to enter the login credentials in paypal sdk web UI

### ISSUE THREAD

**Issue by mpalanisamy-concentrix** [paypal/paypalcheckout-ios#137]
### 🐞 Describe the Bug
@jonathajones  In an iPad device when the user is trying to log in with PayPal credentials on the PayPal SDK web UI no keyboard pops up to enter the login credentials.

### 🔬 Minimal Reproduction
Go to the checkout page and click the PayPal checkout button sdk will ask to enter the login credentials. No keyboard is popping up to enter the credentials. 

### 😕 Actual Behavior
To enter the login credentials keypad is not popping up.

### 🤔 Expected Behavior
The keyboard should pop up to enter the login credentials.

### 🌍 Environment

- iOS version: iPad 5th Gen iOS 15.X
- SDK version (`Checkout. version`): - V0.110.0

### ➕ Additional Context
Due to this not able to proceed with the paypal flow in the iPad device.

https://user-images.githubusercontent.com/105424366/222431957-72559dc9-e783-4d9e-bfc7-15ba9689ae32.MP4

**Comment by jonathajones** [comment]
Hi @mpalanisamy-concentrix - Just to clarify, this is a physical device and not a simulator, correct?

**Comment by mpalanisamy-concentrix** [comment]
@jonathajones  yes it's a physical device.

**Comment by stephaniechiu** [comment]
@mpalanisamy-concentrix - Have you tried the checkout flow with Bluetooth turned off (in case it's connected to a wireless keyboard) and turning your iPad on/off? We tested internally to try an replicate the keyboard not showing and couldn't

**Comment by stechiu** [comment]
@mpalanisamy-concentrix We investigated on our end and couldn't replicate the issue. Can you please try logging in again after restarting your device and make sure it's not connected to a bluetooth or external keyboard?

**Comment by stechiu** [comment]
@mpalanisamy-concentrix Following up - Are you still seeing the keyboard issue on iPad?

**Comment by mpalanisamy-concentrix** [comment]
@stechiu  yes, still facing the issue.

**Comment by stechiu** [comment]
@mpalanisamy-concentrix In the upcoming release, if buyers checkout using PayPal on iPad, they will be taken to the webview rather than the NXO experience, so the keyboard issue won't be a problem.

**Comment by stechiu** [comment]
In the upcoming release, if buyers checkout using PayPal on iPad, they will be taken to the webview rather than the NXO experience, so the keyboard issue won't be a problem.
