### ISSUE TITLE
[🚀] How to enable pickup option from the SDK config

### ISSUE THREAD

**Issue by mpalanisamy-concentrix** [paypal/paypalcheckout-ios#138]
### 🚀 Feature Request

@jonathajones  There is a requirement in my project I have to get pickup information(firstname, lastname, phonenumber) for my product to complete the order. 

### Motivation

Is there any feature available to get the pickup information from the user from the sdk UI. Also, need to hide the shipping address information for the particular pickup scenario.

### Example

ApplePay we have a similar feature to get the pickup/contact information.
![Simulator Screen Shot - iPhone 14 - 2023-03-07 at 09 33 59](https://user-images.githubusercontent.com/105424366/223317918-67a42067-3274-49a1-a829-226e7013a6a0.png)

**Comment by stechiu** [comment]
@mpalanisamy-concentrix To enable the pickup option, create another `ShippingMethod` shipping option that has shipping type is set to `.pickup`. Make sure to have exactly one shipping option with `selected: true` as a default option if you have both shipping and pickup options.

Once a user taps on the "Review Order" button, they will be taken back to the merchant's order screen where the user will be able to pass along their order info (including name, phone number, email) when they checkout on the merchant's app.

**Comment by mpalanisamy-concentrix** [comment]
@stechiu, what is the shipping preference we have to configure for PickUp orders, and there is no UI on PayPal SDK to capture the name, phone, email information as in the ApplePay.

**Comment by stechiu** [comment]
@mpalanisamy-concentrix To set Pickup orders to the default shipping method, set the pickup option to `selected: true` and set the shipping option to `selected: false`. Did you enable "Contact Telephone Number" under Profiles & Settings in the merchant's account before passing in the `phone` object in the Orders API? https://developer.paypal.com/docs/api/orders/v2/#orders_confirm. Once you do that, you can capture the payer's name, phone, and email. Phone doesn't show on the SDK

**Comment by mpalanisamy-concentrix** [comment]
@stechiu  can we get the detailed configuration(shipping preference type, where we need to set pickup option, any other config that need for the paypal order request) for the pickup order?

**Comment by stechiu** [comment]
@mpalanisamy-concentrix Thanks for the details. I'll be addressing the pickup here since the phone one is a separate issue. Here's sample code:

```
  private func configurePayPalCheckout() {
    let config = CheckoutConfig(
      createOrder: { ... },
      onShippingChange: { change, action in
        let shippingOptions = [
            ShippingMethod(
              id: "1",
              label: "Pickup",
              selected: true,
              type: .pickup,
              amount: UnitAmount(currencyCode: .usd, value: "0")
            ),
            ShippingMethod(
              id: "2",
              label: "Shipping",
              selected: false,
              type: .shipping,
              amount: UnitAmount(currencyCode: .usd, value: "0")
            ),
        ]
        let patchRequest = PatchRequest()
        patchRequest.add(shippingOptions: shippingOptions)

        action.patch(request: patchRequest) { success, error in
        }
      },
```

Patch Order Documentation: https://developer.paypal.com/docs/api/orders/v2#orders_patch. This enables adding `patchRequest.add` or removing `patchRequest.remove` shipping options, shipping addresses, and shipping names (`[ShippingMethod]`, `OrderAddress`, `PurchaseUnit.ShippingName`)


https://user-images.githubusercontent.com/127455800/225984459-bb21c7df-dd42-4ca4-a71e-24e66130137b.mov

**Comment by stechiu** [comment]
@mpalanisamy-concentrix Following up, were you able to configure pickup?

**Comment by mpalanisamy-concentrix** [comment]
@stechiu , still facing an issue with the shipping method option as .pickup.

**Comment by stechiu** [comment]
@mpalanisamy-concentrix Can you share a code snippet of how you're creating the pickup shipping option?

**Comment by devchristina** [comment]
Is this still an issue? If no response received by 10/27, issue will be closed as not planned.
