### ISSUE TITLE
Native UI never displays

### ISSUE THREAD

**Issue by martinprot** [paypal/paypalcheckout-ios#14]
I'm starting the checkout native the simplest way, as explained in the documentation
https://paypal.github.io/paypalnativecheckout-docs/iOS/invoking_sdk/

```
	PYPLCheckout* checkout = [PYPLCheckout sharedInstance];
	// checkout.webBrowserOnlyMode = @NO; // tried with and without this, with the same result.
	checkout.delegate = self;
```

Safari View Controller always pops up (No Native UI Mode). Also tried with wabview interception with the same results.

**Comment by dmikey** [comment]
Hey @martinprot SFVC should pop up to authenticate the user into the PayPal system. Due to the nature of mobil devices we need to complete an `oauth` request using SFVC. The return will come to the approved Universal Link URL. When this is successful the SDK will attempt to launch the native experience.

**Comment by dmikey** [comment]
@martinprot pinging you again, feel free to email me directly dereanderson (at) paypal.com

Thanks!

**Comment by martinprot** [comment]
hello @dmikey, since we had a very short delay to launch the update (as usual...), we switched to a web based version of paypal. But I will try to install paypalcheckout-ios as soon as possible to try again.

**Comment by jkblgithub** [comment]
hi @martinprot 

Can you perhaps give me some pointers on how you integrated a web based version in your app. We have tried but the paypal iframe/popup does not work. Any tips on how you did it would be really appreciated please.
