### ISSUE TITLE
[🐞] PayPal sheet closes after submitting the login form in react native app

### ISSUE THREAD

**Issue by youedd** [paypal/paypalcheckout-ios#140]
### 🐞 Describe the Bug

I am currently using the Checkout SDK in a `react native` app as an [iOS native module](https://reactnative.dev/docs/native-modules-ios#create-custom-native-module-files).

The PayPal sheet automatically closes after submitting the login form.

I tested the older versions of the SDK, and noticed that v0.101.0 and below don't have this issue.

### 🔬 Minimal Reproduction
I created a minimal repository with react native cli boilerplate and  checkout SDK.
To reproduce:
- fork https://github.com/youedd/react-native-paypal-checkout-ios-example
- open a terminal from the repository root folder
- `npm install`
- `cd ios`
- `pod install`
- open `ios/paypalCheckoutExample.xcworkspace` with xcode
- change the clientID in RNPaypalCheckout.swift` and run the project
- start the checkout, enter an email and submit

### 😕 Actual Behavior
The PayPal sheet closes immediately after submitting the form

### 🤔 Expected Behavior
The PayPal sheet should not close 

### 🌍 Environment

- iOS version: - iOS 16
- SDK version (`Checkout.version`): - v0.110.0

### ➕ Additional Context
https://user-images.githubusercontent.com/19575877/224483956-bb8fc992-13d3-483a-a14d-91a406446621.mov

**Comment by youedd** [comment]
I also noticed that `onCancelCallback` is triggered when the PayPal sheet closes.

**Comment by zhou0506** [comment]
How did you solve it？

**Comment by youedd** [comment]
We downgraded to the `v0.101.0` for the moment @zhou0506

**Comment by zhou0506** [comment]
@youedd ok 👍🏻👍🏻👍🏻

**Comment by KovtunOleg** [comment]
We had the same issue on the 1.1.0 version, so we decided to downgrade to the `0.109.0`. Thanks to @youedd addvice

**Comment by devchristina** [comment]
Closing this issue, not planned.
