### ISSUE TITLE
[🐞] Skipping express checkout for future payments results into permission error

### ISSUE THREAD

**Issue by coreioscoder** [paypal/paypalcheckout-ios#142]
### 🐞 Describe the Bug
We are currently trying to include the native checkout for iOS into our app. 
When during the checkout the user tries to skip the express checkout, then the checkout always results into an error. It seems like after pressing the "Not now" - Link the process changes the store context (The user also has to login again). When you watch the video you can see at the bottom the store brand in the beginning it is "TheBestApp" (That app name we used for this example in the paypal developer console) and after skipping the express checkout option it is "Test Store".

https://user-images.githubusercontent.com/129072903/227957650-c2d702b0-b16c-4cbd-b7e3-220484f5ccff.mov

The error always is:
```
(lldb) po error
▿ Optional<Error>
  ▿ some : OrderActionError
    ▿ errorAuthorizingFunds : 5 elements
      ▿ 0 : 2 elements
        - key : "name"
        - value : NOT_AUTHORIZED
      ▿ 1 : 2 elements
        - key : "links"
        ▿ value : 1 element
          ▿ 0 : 2 elements
            ▿ 0 : 2 elements
              - key : rel
              - value : information_link
            ▿ 1 : 2 elements
              - key : href
              - value : https://developer.paypal.com/docs/api/orders/v2/#error-PERMISSION_DENIED
      ▿ 2 : 2 elements
        - key : "message"
        - value : Authorization failed due to insufficient permissions.
      ▿ 3 : 2 elements
        - key : "debug_id"
        - value : e50e6e55cd3a9
      ▿ 4 : 2 elements
        - key : "details"
        ▿ value : 1 element
          ▿ 0 : 2 elements
            ▿ 0 : 2 elements
              - key : issue
              - value : PERMISSION_DENIED
            ▿ 1 : 2 elements
              - key : description
              - value : You do not have permission to access or perform operations on this resource.
```

When the user grants the express checkout for future payments everything works as expected. We already tried to work with a returnUrl, but it does not solve our problem.

Is there a way to disable the express checkout or to even force it?

We would greatly appreciate any help regarding this issue.

### 🔬 Minimal Reproduction

Use checkout and press "Not now" when additional permission for express checkout for future payments (not sure what it is called in english) is requested.

![image|](https://user-images.githubusercontent.com/129072903/227949256-62c54de0-1ecf-4605-8064-49f9649142a9.png)

### 🤔 Expected Behavior

Checkout should complete even if the user decides to skip express checkout for future payments.

### 🌍 Environment

- iOS version: 16.2
- SDK version (`Checkout.version`): 0.110.0

### ➕ Additional Context
This example is created with the official example app (paypal/paypalcheckout-samples-ios) with updated PayPalCheckout version 0.110.0, but the behavior is exactly the same with our own app.

**Comment by jonathajones** [comment]
Hi @coreioscoder - thanks for reporting this! We're investigating and will get back to you with questions if we have any.

**Comment by Charles-Berghausen** [comment]
Hey @coreioscoder, sorry for the very late response. We had some trouble reproducing the issue, but think it might have to do with the configuration steps for PayPalCheckout. Could you attach your code for all of the methods you're calling on `Checkout`? (your config and the callbacks you are passing in)

I think paypalcheckout-samples-ios is out of date and we'll need to update it after solving your issue!

**Comment by devchristina** [comment]
Closing this issue as not planned due to lack of response.
