### ISSUE TITLE
[🐞] Invalid Scope error for prod/live environment login

### ISSUE THREAD

**Issue by mpalanisamy-concentrix** [paypal/paypalcheckout-ios#143]
### 🐞 Describe the Bug
 When login in with production credentials with PayPal checkout sdk action sheet we are getting the invalid scope error after login.
 Error in both cases login with password as well sms code option.

### 🔬 Minimal Reproduction
Launch the merchant app and go to the cart page and select PayPal checkout action then enter PayPal live credential and then the error screen will be displayed.

### 😕 Actual Behavior
Not able to login successfully with prod credential, getting the error screen.

### 🤔 Expected Behavior
Should log in successfully and load the PayPal action sheet with order details in the PayPal sdk UI.

### 🌍 Environment
Live environment

- iOS version: all iOS version
- SDK version (`Checkout. version`): - v0.110.0

### ➕ Additional Context

![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/105424366/228499200-71f9f821-2836-4b44-9dd5-415c7fd74dae.png)
![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/105424366/228499225-8df9a58f-7fb8-4654-bebd-3f7c02b5bd8b.png)

**Comment by jonathajones** [comment]
Hi @mpalanisamy-concentrix - 
On your developer dashboard (logging in at developer.paypal.com) - navigate to your production app associated with your client ID scroll to the app settings. Ensure that the `Native Checkout SDK` box is enabled: 

![image](https://user-images.githubusercontent.com/74559931/228558642-8bf8b968-ed9a-4c50-a5f4-2e2d4bdcae5a.png)

In the same menu, ensure that 'Login with PayPal' is enabled: 
![image](https://user-images.githubusercontent.com/74559931/228558939-0f8bcac4-0573-4e7e-a803-78c068dca7e7.png)

This should resolve the scope issue you're seeing.
