### ISSUE TITLE
[🐞] iOS 12.x Crash on login interaction

### ISSUE THREAD

**Issue by ndilworth** [paypal/paypalcheckout-ios#144]
### 🐞 Describe the Bug
When interacting with the native SDK that involves launching the web (assuming this is the issue), causes an app crash. This does not occur on iOS 11 or iOS 13+, only on iOS 12.

### 🔬 Minimal Reproduction
iOS 12.x
iOS SDK 109 and 110
Flutter 3.3.9
1. Start Checkout 
2. Native SDK login sheet appears
3. Enter email, click next
4. Click Use Password
5. App Crash

### 😕 Actual Behavior
SDK causing app crash during login process

### 🤔 Expected Behavior
Not crash

### 🌍 Environment

- iOS version: - 12.x
- SDK version (`Checkout.version`): - 109, 110
- Sandbox Account
- Flutter 3.3.9

### ➕ Additional Context
Case 1 - Using an unregistered sandbox email address
1. Enter the email address, click next, crash
<img width="560" alt="Screen Shot 2023-04-12 at 2 01 54 PM" src="https://user-images.githubusercontent.com/1034101/231584930-58b51eaa-2fec-42d2-976c-f3ded7ba6cf3.png">

default	14:01:56.370600-0700	Runner	*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIApplication connectedScenes]: unrecognized selector sent to instance 0x7fc003d015c0'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000113b7c8db __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000112ce1ac5 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000113b9ac94 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   UIKitCore                           0x0000000122fb6235 -[UIResponder doesNotRecognizeSelector:] + 287
	4   CoreFoundation                      0x0000000113b81623 ___forwarding___ + 1443
	5   CoreFoundation                      0x0000000113b83418 _CF_forwarding_prep_0 + 120
	6   PayPalCheckout                      0x000000011084e65b __62-[PFPartnerAuthenticationProvider webLogIn:completionHandler:]_block_invoke + 84
	7   libdispatch.dylib                   0x00000001173e4ccf _dispatch_call_block_and_release + 12
	<…>

Case 2 - Using a valid sandbox email address
1. Enter the email address, click next, 
2. Receive prompt for sending phone code
3. Click use password instead, crash
<img width="532" alt="Screen Shot 2023-04-12 at 2 07 49 PM" src="https://user-images.githubusercontent.com/1034101/231585971-a77e6d44-9168-4658-8431-377399fe9864.png">
<img width="541" alt="Screen Shot 2023-04-12 at 2 07 56 PM" src="https://user-images.githubusercontent.com/1034101/231585985-cca5700f-1de1-40fe-80b0-6913b23f4c0a.png">

default	14:08:18.111242-0700	Runner	*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIApplication connectedScenes]: unrecognized selector sent to instance 0x7f7f3e702b40'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001178478db __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x00000001169acac5 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000117865c94 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   UIKitCore                           0x0000000126c81235 -[UIResponder doesNotRecognizeSelector:] + 287
	4   CoreFoundation                      0x000000011784c623 ___forwarding___ + 1443
	5   CoreFoundation                      0x000000011784e418 _CF_forwarding_prep_0 + 120
	6   PayPalCheckout                      0x000000011451965b __62-[PFPartnerAuthenticationProvider webLogIn:completionHandler:]_block_invoke + 84
	7   libdispatch.dylib                   0x000000011b0afccf _dispatch_call_block_and_release + 12
	<…>

**Comment by jonathajones** [comment]
Hi @ndilworth  - Thanks for reporting this issue, and some context: 
Before identifying the issue, we had already been planning to increment our minimum iOS target version to 13. The root issue here is that an underlying dependency inappropriately references an iOS 13 specific symbol, even though we had support for iOS 12 - but given our plans to increase our minimum iOS target (and the vanishingly small percentage of our users on iOS 12) , it was not practical to resolve this in the underlying dependency. We will be releasing another version at the end of this month with the incremented minimum iOS target.  

To avoid this issue, I suggest falling back to a web experience for users on iOS 12 in the meantime. Apologies for the bad experience here!
