### ISSUE TITLE
How to switch languages

### ISSUE THREAD

**Issue by ZXiaoPang** [paypal/paypalcheckout-ios#145]
### Describe Your Issue
I'm switching between other languages in the app. How to modify the language of papal payment page when I reset the papal payment page

**Comment by stechiu** [comment]
Hi @ZXiaoPang, the language of the SDK paysheet is automatically updated once you or your customers change the device's language under Setting > general > Language & Region

Let me know if this helps

**Comment by ZXiaoPang** [comment]
Ok, I thought we would switch languages depending on the APP, and SKDS
would follow.

Stephanie ***@***.***> 于2023年4月19日周三 06:06写道：
