### ISSUE TITLE
[🐞] Bug Report Random redirecting on web checkout and cartId missing on call back

### ISSUE THREAD

**Issue by tacktackroom** [paypal/paypalcheckout-ios#148]
Hey there,

### 🐞 Describe the Bug
Randomly redirected on web when call the API. either I'm logged in or not.
If I complete a purchase from the web UI, the cartId data is missing and the order fails.
It goes fine with the native checkout

### 🔬 Minimal Reproduction
Describe steps to reproduce. 

### 🤔 Expected Behavior
force to stay native and if I want to go web, get the cardid

### 🌍 Environment

- iOS version: 16-1
- SDK version (`Checkout.version`): 0.112-1

### ➕ Additional Context

https://github.com/paypal/paypalcheckout-ios/assets/58400212/76723e24-9c82-4cfa-9d27-32eb35b70b97

thank you!

**Comment by devchristina** [comment]
Closing this issue as not planned due to lack of response.
