### ISSUE TITLE
¿where can I find my payment_token?

### ISSUE THREAD

**Issue by jorgemendiza** [paypal/paypalcheckout-ios#15]
Hello, I did the integration of this sdk but I don´t know where can I find the payment token. 

PYPLCheckout* checkout = [PYPLCheckout sharedInstance];
checkout.webBrowserOnlyMode = @YES;
[checkout startCheckoutWithECToken:@"provide_payment_token" withDelegate:self];

I only find Client ID and Secret. When I set some of them I get the next result: (invalid scope). 

Thanks.

**Comment by dmikey** [comment]
The payment token is generated by some back-end system. You could be using PayPal Rest API directly, or you may currently already have a payment gateway that generates a Payment token, or a PayPal URL, that will have the token as part of the URL.

**Comment by jorgemendiza** [comment]
Thanks dmikey. I´m trying to do this with my app. I had implemented the Authorization process and I get the token successfully, now after call "https://api.sandbox.paypal.com/v1/payments/payment" with "intent": "authorize" I get a successfully response but I don't get any payment token. Can you guide me a little bit please? I had read the docs but I don't know how I can get a token. 

Cheers from Mexico!
![simulator screen shot - iphone xr - 2018-12-26 at 10 50 16](https://user-images.githubusercontent.com/3135485/50451835-23fbdc00-08fc-11e9-948f-a351b6842441.png)

**Comment by dmikey** [comment]
@jorgemendiza my apologies for not seeing these updates. Currently, we're working on getting this scope enabled for self serve, and onboarding merchants slowly. 

If you have a PayPal Relationship Manager, please reach out to them. Thanks!
