### ISSUE TITLE
error generating LSAT [🐞] Bug Report

### ISSUE THREAD

**Issue by AhmedShanab74** [paypal/paypalcheckout-ios#154]
### 🐞 Describe the Bug
i try to complete Purchase but i have  " error generating LSAT " message 

### 🔬 Minimal Reproduction

  func triggerPayPalCheckout() {
        guard let order = createNewOrder() else {
            print("can't create order")
            return
}
         Checkout.start(
           createOrder: { action in
             action.create(order: order) { orderId in
               if orderId == nil {
                 print("There was an error with the format of your order object")
               }
               else {
                 print("Order created with order ID \(String(describing: orderId))")
               }
             }
           },
           onApprove: { approval in
             self.processOrderActions(with: approval)
           },
           onCancel: {
             print("Checkout cancelled")
           },
           onError: { errorInfo in
             print("correlationIDs: \(errorInfo.correlationIDs)")
             print("Checkout failed with error info \(errorInfo.error.localizedDescription)")
           }
         )
               
    }

### 🌍 Environment

- iOS version: - 16.4
- SDK version (`Checkout.version`): -  0.112.2

### ➕ Additional Context

https://github.com/paypal/paypalcheckout-ios/assets/128382748/5a21ae89-cff7-4814-8cff-0c0e7262d81e

Add any other context about the problem here. Screenshots or videos that show the issue are very helpful.

**Comment by AhmedShanab74** [comment]
@Charles-Berghausen is there any way to share my code with you to check what cause the error ?

**Comment by Charles-Berghausen** [comment]
Hi @AhmedShanab74, is this the first time you are adopting paypal native checkout in your app? You should do this with the Braintree iOS SDK instead, which I linked info for above. PayPal is no longer supporting new developers integrating directly with our SDK through this paypalcheckout-ios repo
