### ISSUE TITLE
[🐞] Cocoapods sdk missing

### ISSUE THREAD

**Issue by harrowmykel** [paypal/paypalcheckout-ios#156]
The latest version of this sdk on cocoapods is version 0.109.0

Please add version 1.1.0

![image](https://github.com/paypal/paypalcheckout-ios/assets/22492933/d8a1b25a-dd5e-423e-a89d-34f18fd55e0a)

**Comment by jonathajones** [comment]
Hi @harrowmykel - The remote spec is available already here: https://github.com/CocoaPods/Specs/blob/master/Specs/1/0/c/PayPalCheckout/1.1.0/PayPalCheckout.podspec.json

I'm not sure why the search interface only shows the availability of the 0.110.0 version of the SDK.

**Comment by harrowmykel** [comment]
What does that mean?

How Do I update to Version 1.1.0? It's not getting installed

**Comment by harrowmykel** [comment]
Thanks a lot for the comment but that worked but did not solve the problem. 

I had to add
```
platform :ios, '13.0' 
```
to my Podfile. There is a lock that makes the plugin unavailable to projects target the minimum requirement

**Comment by jonathajones** [comment]
I'm not clear on the issue you're facing - what is the minimum iOS target of your app? Our SDK requires a minimum iOS target of 13.0

**Comment by harrowmykel** [comment]
It was 11.0 but I updated it to 13 and now it works fine.

It's for the flutter plugin flutter_paypal_native.

You may close this issue as resolved
