### ISSUE TITLE
Docs missing iOS 12 in feature table

### ISSUE THREAD

**Issue by Jinchauhan** [paypal/paypalcheckout-ios#16]
https://paypal.github.io/paypalnativecheckout-docs/iOS/getting_started/

The getting started page doesn't have iOS 12 in the feature support table.

**Comment by dmikey** [comment]
Thanks we will get this updated!

**Comment by dmikey** [comment]
This has been updated with-in out limited release documentation. Feel free to message me dereanderson (at) paypal (dot) com , and I'll be more than happy to share. Closing this issue.
