### ISSUE TITLE
[🐞] Bug Report

### ISSUE THREAD

**Issue by Cniklasson** [paypal/paypalcheckout-ios#162]
### 🐞 Describe the Bug

![IMG_3694](https://github.com/paypal/paypalcheckout-ios/assets/148633934/80e26de4-cee2-4547-9e02-f65d4e001d6f)

### 🔬 Minimal Reproduction
#Describe steps to reproduce. 

Do you have any ideas why this happening? I have my developers trying to solve the problem but still no luck.

### 😕 Actual Behavior
A clear and concise description of what is happening. Please debugger logs and error messages if applicable.

[crashlog-B9ACBF3D-AF1B-4492-A279-D63C7BF02EE4.txt](https://github.com/paypal/paypalcheckout-ios/files/13190379/crashlog-B9ACBF3D-AF1B-4492-A279-D63C7BF02EE4.txt)

Error when uploading build. After PayPal iOS SDK is integrated. App crash in startup. Worked smoothly before Paypal SDK

### 🤔 Expected Behavior

To run smoothly..

### 🌍 Environment

- iOS version: - 17.0.3
- SDK version (`Checkout.version`): -

**Comment by jonathajones** [comment]
Hi @Cniklasson - What version of the Checkout SDK are you integrating?

**Comment by jonathajones** [comment]
Please try with version `1.1.0` of the SDK and report back here if you are still seeing the same upload issue.

**Comment by Cniklasson** [comment]
> Hi @Cniklasson - What version of the Checkout SDK are you integrating?

Sorry for late reply. Developer had some days off.

Version 
0.102.0

**Comment by jonathajones** [comment]
This was resolved in version `0.106.0`. Please update to `1.1.0`. This will fix the unsupported bundle structure issue you're seeing.
