### ISSUE TITLE
[🐞] Bug Report

### ISSUE THREAD

**Issue by Cniklasson** [paypal/paypalcheckout-ios#163]
### 🐞 Describe the Bug

![IMG_3877](https://github.com/paypal/paypalcheckout-ios/assets/148633934/36f9bb5f-5190-4d76-a6a4-2dbeb6402760)

### 🔬 Minimal Reproduction
Describe steps to reproduce. 

We updated the PayPal SDK version 0.102.0 because we had the same error. We got advice to update to 1.1.0 but we still have same error when uploading. 

### 😕 Actual Behavior
A clear and concise description of what is happening. Please debugger logs and error messages if applicable.

Error when uploading build. After PayPal iOS SDK is integrated. Error when uploading to TestFlight. Worked smoothly before Paypal SDK

### 🤔 Expected Behavior

To run smoothly after updating to 1.1.0 from 
0.102.0

### 🌍 Environment

- iOS version: - 17.0.3
- SDK version (`Checkout.version`): - 1.1.0

### ➕ Additional Context
Add any other context about the problem here. Screenshots or videos that show the issue are very helpful.

**Comment by jonathajones** [comment]
@Cniklasson - We have internally uploaded to testflight without issue on version 1.1.0, and numerous other merchants are also deployed using 1.1.0 - so it's strange that you're seeing this.

Could you validate that the version you're uploading actually has the correct version of Checkout bundled with it? You can verify by doing the following: 

1. Inspect the contents of the `.ipa` file you're uploading (you can do this by changing the file type to .zip and opening like any other zip file)
2. Right click your app in finder and select `Show Package Contents`
3. Navigate to `Frameworks/PayPalCheckout.framework`
4. Open the `Info.plist`
5. Check the value of `Bundle version string (short)` 

If the value of this key is `1.1.0`, then you should not see the upload errors you're encountering via testflight. If you continue to see this after validating you're installing the correct version of PayPalCheckout - would you be able to reproduce in a sample app and share that with me? 

Thank you!

**Comment by Cniklasson** [comment]
> @Cniklasson - We have internally uploaded to testflight without issue on version 1.1.0, and numerous other merchants are also deployed using 1.1.0 - so it's strange that you're seeing this.
> 
> Could you validate that the version you're uploading actually has the correct version of Checkout bundled with it? You can verify by doing the following:
> 
> 1. Inspect the contents of the `.ipa` file you're uploading (you can do this by changing the file type to .zip and opening like any other zip file)
> 2. Right click your app in finder and select `Show Package Contents`
> 3. Navigate to `Frameworks/PayPalCheckout.framework`
> 4. Open the `Info.plist`
> 5. Check the value of `Bundle version string (short)`
> 
> If the value of this key is `1.1.0`, then you should not see the upload errors you're encountering via testflight. If you continue to see this after validating you're installing the correct version of PayPalCheckout - would you be able to reproduce in a sample app and share that with me?
> 
> Thank you!







> @Cniklasson - We have internally uploaded to testflight without issue on version 1.1.0, and numerous other merchants are also deployed using 1.1.0 - so it's strange that you're seeing this.
> 
> Could you validate that the version you're uploading actually has the correct version of Checkout bundled with it? You can verify by doing the following:
> 
> 1. Inspect the contents of the `.ipa` file you're uploading (you can do this by changing the file type to .zip and opening like any other zip file)
> 2. Right click your app in finder and select `Show Package Contents`
> 3. Navigate to `Frameworks/PayPalCheckout.framework`
> 4. Open the `Info.plist`
> 5. Check the value of `Bundle version string (short)`
> 
> If the value of this key is `1.1.0`, then you should not see the upload errors you're encountering via testflight. If you continue to see this after validating you're installing the correct version of PayPalCheckout - would you be able to reproduce in a sample app and share that with me?
> 
> Thank you!

I have forwarded your message to my developers, once i got a reply i let you know directly.

Can i contact you directly somewhere?

**Comment by Cniklasson** [comment]
> > @Cniklasson - We have internally uploaded to testflight without issue on version 1.1.0, and numerous other merchants are also deployed using 1.1.0 - so it's strange that you're seeing this.
> > Could you validate that the version you're uploading actually has the correct version of Checkout bundled with it? You can verify by doing the following:
> > 
> > 1. Inspect the contents of the `.ipa` file you're uploading (you can do this by changing the file type to .zip and opening like any other zip file)
> > 2. Right click your app in finder and select `Show Package Contents`
> > 3. Navigate to `Frameworks/PayPalCheckout.framework`
> > 4. Open the `Info.plist`
> > 5. Check the value of `Bundle version string (short)`
> > 
> > If the value of this key is `1.1.0`, then you should not see the upload errors you're encountering via testflight. If you continue to see this after validating you're installing the correct version of PayPalCheckout - would you be able to reproduce in a sample app and share that with me?
> > Thank you!
> 
> > @Cniklasson - We have internally uploaded to testflight without issue on version 1.1.0, and numerous other merchants are also deployed using 1.1.0 - so it's strange that you're seeing this.
> > Could you validate that the version you're uploading actually has the correct version of Checkout bundled with it? You can verify by doing the following:
> > 
> > 1. Inspect the contents of the `.ipa` file you're uploading (you can do this by changing the file type to .zip and opening like any other zip file)
> > 2. Right click your app in finder and select `Show Package Contents`
> > 3. Navigate to `Frameworks/PayPalCheckout.framework`
> > 4. Open the `Info.plist`
> > 5. Check the value of `Bundle version string (short)`
> > 
> > If the value of this key is `1.1.0`, then you should not see the upload errors you're encountering via testflight. If you continue to see this after validating you're installing the correct version of PayPalCheckout - would you be able to reproduce in a sample app and share that with me?
> > Thank you!
> 
> I have forwarded your message to my developers, once i got a reply i let you know directly.
> 
> Can i contact you directly somewhere?

Jones, developer checked steps 1,2,3,4,5
And they still not get it working. (Yes we tried this too but not worked)

Where can i get in touch?

**Comment by jonathajones** [comment]
Hi @Cniklasson - 
Can you please create a sample project where you reproduce this issue? Given that I cannot reproduce it locally and other teams have successfully migrated to 1.0 and 1.1, I believe it is a local packaging problem. 

If you can share a sample project that reproduces the problem, we'll investigate and reach out with a solution. 

Thanks!
Jon
