### ISSUE TITLE
[🐞] Error after PayPal pod installation.

### ISSUE THREAD

**Issue by Cniklasson** [paypal/paypalcheckout-ios#169]
### 🐞 Describe the Bug

Error message after PayPal pod installation. PayPal Mobile iOS SDK (Native Payments)

### 🔬 Minimal Reproduction

Developer told me error message after pod installation. Developer wrote me ”We are not able to run app because of this error.”

### 😕 Actual Behavior

❌ Framework ”PayPal” not found.
❌ Linker command failed with exit code 1 (use -v to see invocation)

### 🤔 Expected Behavior
The app and PayPal integration to run smoothly.

### 🌍 Environment

- iOS version: - 17.0
- SDK version (`Checkout.version`): -

### ➕ Additional Context
From the very beginning we found out that they have implemented the wrong SDK. Now they have implemented the right SDK and got the error message. 

![IMG_4322](https://github.com/paypal/paypalcheckout-ios/assets/148633934/485b6a54-5ed6-4af4-98ec-e59e438df7b4)

https://developer.paypal.com/beta/advanced-mobile/integrate-ios/

**Comment by jonathajones** [comment]
Hi @Cniklasson - in your Podfile, are you importing PayPalCheckout or the this sdk - https://github.com/paypal/paypal-ios/blob/main/PayPal.podspec ? 

There is a module in the `PayPal` sdk that wraps the behavior in PayPalCheckout. This may be the source of the confusion.
