### ISSUE TITLE
"In-app Checkout" checkbox is missing in Live tab

### ISSUE THREAD

**Issue by ValkA** [paypal/paypalcheckout-ios#17]
In this page:
https://paypal.github.io/paypalnativecheckout-docs/Setup/obtaining_merchant_id/
clause 4 asks to check "In-app Checkout" but the checkbox is missing (in my case).

**Comment by dmikey** [comment]
This is unfortunately correct at this time. We're working on enabling this as a self service option ASAP. We will update our documentation soon.

**Comment by Calvin2274** [comment]
> In this page:
> https://paypal.github.io/paypalnativecheckout-docs/Setup/obtaining_merchant_id/
> clause 4 asks to check "In-app Checkout" but the checkbox is missing (in my case).

same here
