### ISSUE TITLE
Safari cannot continue the checkout

### ISSUE THREAD

**Issue by DaveCC94** [paypal/paypalcheckout-ios#18]
Hi, I'm trying to use the native checkout experience, but once I open the WKWebView and press the continue button, I get an error on safari.

```
        let request =  URLRequest(url: paypalUrl)
        paypalCheckout.delegate = self
        paypalCheckout.webBrowserOnlyMode = true
        paypalCheckout.interceptWebView(webView)
        paypalCheckout.serviceEnvironment = .sandBox
        self.webView.navigationDelegate = self
        self.webView.load(request)
```

This is something that appears on my logs

`https://www.sandbox.paypal.com/cgi-bin/webscr?native_xo=1&redirect_uri=https://paypalxo&cmd=_express-checkout&token=EC-35T70695SS9804308`

I think that the reason why this is failing is because of the redirect_uri, is it really related? what can I do?

Thanks!

**Comment by DaveCC94** [comment]
For those wondering, you have to configure your own URIScheme to make this work, for reference please check:
https://www.appcoda.com/working-url-schemes-ios/

**Comment by dmikey** [comment]
Glad you got this figured out!
