### ISSUE TITLE
Carthage doesn't produce a framework

### ISSUE THREAD

**Issue by rzulkoski** [paypal/paypalcheckout-ios#2]
After adding `github "paypal/paypalcheckout-ios" >= 1.2.0` to a fresh project and running carthage update --platform iOS it finishes successfully but there is no output in the Carthage/Builds/iOS directory.

Any ideas?

Versions:
Carthage 0.25.0
Xcode 9.0 (9A235)
macOS 10.13 High Sierra

**Comment by dmikey** [comment]
Thanks for reporting. We'll make sure to take this into account for our 3.0 beta release. Please wait a little bit longer :) we've got big surprises in store, with a fully native interface. 

Please ping me dereanderson(at)paypal.com , and we'll make sure to loop you in.

**Comment by rzulkoski** [comment]
Hey Derek, do you have an ETA on the 3.0 beta release?
