### ISSUE TITLE
Swift Integration

### ISSUE THREAD

**Issue by taimoorsuleman** [paypal/paypalcheckout-ios#20]
I am unable to integrate in my swift project.

**Comment by wojciechczerski** [comment]
Integration with Swift project should be straightforward. First make sure the SDK is integrated into your project using CocoaPods. When it's done, the next thing you need is a Bridging Header. To create one just add an Objective-C file to your project and Xcode will ask you whether you would like to add a Bridging Header. Select 'Yes' and delete the Obj-C file you added. Now open the Bridging Header file (ends with `-Bridging-Header.h`) and add this line:
```objc
#import <NativeCheckout/PYPLCheckout.h>
```
Now you should be able to access the SDK's classes (e.g. `PYPLCheckout`).

**Comment by taimoorsuleman** [comment]
It Works.
DO you have any sample project for this ?
I did't find any sample/ demo project .
i would be great , if anyone share demo project in swift

**Comment by fbarraganef** [comment]
I'm getting the invalid scope error when I launch the webview with the start(token, delegate) method .  I don't have any idea why is happening.
