### ISSUE TITLE
Duplicate symbols for architecture 

### ISSUE THREAD

**Issue by JDandini** [paypal/paypalcheckout-ios#21]
We got an existing app and we try to add PayPal Checkout but  just at add the pod on the pod file we got this errors
![Screen Shot 2019-04-16 at 11 10 22](https://user-images.githubusercontent.com/2761402/56226114-4004c400-6038-11e9-809d-bb2205154680.png)
I'm not sure but its because have some conflicts with a previous pod installed.
We appreciate your help n this :]

**Comment by JDandini** [comment]
Never mind I notice that I have installed the old SDK so I close the issue

**Comment by dmikey** [comment]
Thanks!
