### ISSUE TITLE
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information

### ISSUE THREAD

**Issue by kushalshah-invx** [paypal/paypalcheckout-ios#24]
Hello,

We are using the latest SDK (3.4.6) in one of the iOS application. While submitting an iOS application in the app store recently we are receiving a warning from the apple team regarding deprecated API usage. 

Warning:
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information

We are using - (void)webView:(WKWebView *)webView
decidePolicyForNavigationAction:(WKNavigationAction *)navigationAction
decisionHandler:(void (^)(WKNavigationActionPolicy))decisionHandler method to avoid the warning. 

While running the 'grep -r "UIWebView" .' command we came to know one of the binary file of PayPal checkout still containing UIWebView. "Binary file ./Pods/PayPal.Checkout/pod/lib/libNativeCheckout.a matches". 

Can you please look into this manner and help us out from this?

Thank you

**Comment by kushalshah-invx** [comment]
Hello Team, 

Can we have a solution for the same, please?

Waiting for your reply.

**Comment by kushalshah-invx** [comment]
Hello Guys,

I will be really helpful if we got a solution to the said issue.

Eagerly waiting for your reply.

Thank you

**Comment by xzenon** [comment]
The same issue. What is the chance to expect the updated version?

**Comment by wbaumgar** [comment]
@vladfilyakov Has this lib been updated to not include UIWebview?

**Comment by vladfilyakov** [comment]
The old SDK is deprecated and no support is provided for it. New SDK is not yet generally available - should come next year.

**Comment by wbaumgar** [comment]
@vladfilyakov So there is going to be no overlap of service between the 2 SDK's ??? Doesn't seem very professional to do that.

**Comment by wbaumgar** [comment]
And also can you atleast put in the readme that it's deprecated???
