### ISSUE TITLE
Some Tutorial how to use

### ISSUE THREAD

**Issue by holbalzs** [paypal/paypalcheckout-ios#29]
Can I ask some help to implement this framework? I read https://developer.paypal.com/docs/limited-release/native-checkout/ios/ docs, but it wasn't enough for me.

I put the framework to the project and set up everything like in the DOCS

Config part was okey but

Module 'PayPalCheckout' has no member named 'start'
Module 'PayPalCheckout' has no member named 'set'

error messages appears.

**Comment by wbaumgar** [comment]
@vladfilyakov Could you tell us where we can find a tutorial to use this framework?

**Comment by vladfilyakov** [comment]
Thank you for your interest in PayPalCheckout SDK. This framework in not generally available yet for broad consumption. Only select merchants are allowed to use it.

**Comment by vladfilyakov** [comment]
Here is a repo with sample apps for now:
https://github.com/paypal/paypalcheckout-samples-ios

We hope to open this SDK for all merchants next year.

**Comment by wbaumgar** [comment]
@vladfilyakov What is the process of becoming a "select" merchant?
