### ISSUE TITLE
Is this depreciated?

### ISSUE THREAD

**Issue by wbaumgar** [paypal/paypalcheckout-ios#31]
Hi, 

I just wanted to know if this is actually depreciated. There is nothing on the Readme that explicitly says that this is no longer supported. But whenever I try to use this package I'm getting an "invalid scope" error. 

Please advise, 

Best, 
Will

**Comment by jonathajones** [comment]
Hi @wbaumgar  - 
This project was very recently moved from limited release to general availability. You can find our release documentation [here](https://developer.paypal.com/docs/business/native-checkout/ios/). 
Moving forward, we're going to be much more active here in both support, presence here, and documentation with the Checkout SDK.
