### ISSUE TITLE
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information

### ISSUE THREAD

**Issue by arminDev** [paypal/paypalcheckout-ios#32]
Hi
I reopen this ticket issue since deadline is coming soon. 
We are using the latest SDK (3.4.6) in one of the iOS application. While submitting an iOS application in the app store recently we are receiving a warning from the apple team regarding deprecated API usage.

Warning:
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information

We are using - (void)webView:(WKWebView *)webView
decidePolicyForNavigationAction:(WKNavigationAction *)navigationAction
decisionHandler:(void (^)(WKNavigationActionPolicy))decisionHandler method to avoid the warning.

While running the 'grep -r "UIWebView" .' command we came to know one of the binary file of PayPal checkout still containing UIWebView. "Binary file ./Pods/PayPal.Checkout/pod/lib/libNativeCheckout.a matches".

@vladfilyakov, @knzknz   Do you have estimated release date for new SDK? 

Kind Regards

**Comment by CRoig** [comment]
I have just downloaded version 0.20.0 and `grep -r "UIWebView .` did not throw anything, so I guess this one in compliant. Can you please check it out? I am having the same problem with Apple.

**Comment by jonathajones** [comment]
The Checkout SDK has only just moved from limited release to general availability - we've moved from a web based flow to an in context native UI experience. Old attempts at Native Checkout (which contained the deprecated `UIWebView` flows) have been unpublished, as they were not fully supported yet. You can find the documentation for the updated SDK [here](https://developer.paypal.com/docs/business/native-checkout/ios/) - and you can trust that we'll be much more active on this board to provide support and resolve issues.
