### ISSUE TITLE
PayPalCheckout.SDKGeneralErrors error 3

### ISSUE THREAD

**Issue by CRoig** [paypal/paypalcheckout-ios#33]
Can you please advice which is the root cause of that error code?

**Comment by jaxdesmarais** [comment]
Hello @CRoig -

The `SDKGeneralErrors` error 3 corresponds to the error case `unknownError` with the error reason "Data missing" and is typically thrown when some sort of configuration data is missing when starting the SDK. I would recommend checking out our newly release [developer documentation](https://developer.paypal.com/docs/business/native-checkout/ios/) for details on setting up and starting the SDK.

We recently moved the SDK from limited-release to general availability. We'll be much more active responding to issues going forward - I'm going to close this issue for now. If you continue to have issues after updating the SDK, please feel free to reopen this issue or opening a new issue with additional details.
