### ISSUE TITLE
invalid client_id or redirect_uri issue

### ISSUE THREAD

**Issue by AppalaNaidu01** [paypal/paypalcheckout-ios#36]
- While I was testing with a sandbox account this is showing up.
- This is what i used:
`let config = Config(clientID: Constants.Paypal_Client_ID, payToken: token, universalLink: "", uriScheme: "myapp", onApprove: { (approvalData) in
                            print("\(approvalData.ecToken)")
                        }, onCancel: {
                            print("Cancelled")
                        }, onError: { (errorInfo) in
                            print("\(errorInfo.correlationIDs.description)")
                        },
                        environment: .sandbox)
                        config.presentingViewController = self
                        Checkout.set(config: config)
                        Checkout.start(experience: .native)`
![Simulator Screen Shot - iPhone 12 Pro - 2021-01-28 at 11 53 09](https://user-images.githubusercontent.com/66260142/106105499-19ab0c80-616a-11eb-97fb-83a64beba18b.png)

**Comment by AppalaNaidu01** [comment]
@gbramwell @burnto  @rsdighe76 @nyteshade      please confirm what I am doing wrong.
After integrating the sdk, I followed these steps to complete checkOut in my code.
1.  Just passed clientId, payToken, uriScheme  in the Config()
2. Then I provided presentation view controller for paypal Check out
3. At last I provided environment as native.

**Comment by AppalaNaidu01** [comment]
I am getting this in my debugger

[TableView] Warning once only: UITableView was told to layout its visible cells and other contents without being in the view hierarchy (the table view or one of its superviews has not been added to a window). This may cause bugs by forcing views inside the table view to load and perform layout without accurate information (e.g. table view bounds, trait collection, layout margins, safe area insets, etc), and will also cause unnecessary performance overhead due to extra layout passes. Make a symbolic breakpoint at UITableViewAlertForLayoutOutsideViewHierarchy to catch this in the debugger and see what caused this to occur, so you can avoid this action altogether if possible, or defer it until the table view has been added to a window. Table view: <PayPalCheckout.PaysheetContainerView: 0x1065a2000; baseClass = UITableView; frame = (0 961.5; 768 38.5); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x2961f6e50>; layer = <CALayer: 0x292b90860>; contentOffset: {0, 0}; contentSize: {768, 0}; adjustedContentInset: {0, 0, 0, 0}; dataSource: <PayPalCheckout.ContainerVM: 0x292b90f80>>

**Comment by jonathajones** [comment]
Hi @AppalaNaidu01  - 

Sorry for the long delayed response. When integrating with the checkout SDK, the `CheckoutConfig` object needs your `clientID` and `returnUrl` (formerly named `uriScheme`). The value supplied for the `returnUrl` must match what is set in your developer console under the `Return URL` section: 

<img width="691" alt="image" src="https://user-images.githubusercontent.com/74559931/114208845-8e958200-9923-11eb-9c45-1f5502529e8c.png">

We've only recently moved from `limited-release` to general availability. We'll be much more active responding to issues and questions here going forward - I'm going to close this issue for now, but please reopen if you have persistent questions. You might also find our new [dev documentation](https://developer.paypal.com/docs/business/native-checkout/ios/) helpful.

To

**Comment by AppalaNaidu01** [comment]
Thanks @jonathajones for the reply.

I found it and fixed, our is published too. Cheers🍻
