### ISSUE TITLE
'PYPLTransaction.h' file not found

### ISSUE THREAD

**Issue by ase-wtag** [paypal/paypalcheckout-ios#4]
Hi,

I am trying to integrate PayPal SDK on my iOS app. But the build is failed because of a missing file named "PYPLTransaction.h". It's being used in "PYPLCart.h". Can you give me a solution for this?

Best,
Amit

**Comment by dmikey** [comment]
Thanks @ase-wtag we will take a look right away, this portion of the SDK is currently undocumented. Thanks for pointing out the missing header.

**Comment by dmikey** [comment]
Please find PYPLTransaction in the latest 3.1.1 release. Thanks!
