### ISSUE TITLE
Missing translated strings from cancelation alert

### ISSUE THREAD

**Issue by SerggioC** [paypal/paypalcheckout-ios#41]
Hello,

Checkout the screenshot. When you tap outside the PayPal bottom sheet to cancel, the alert message has non translated strings. Phone Language is PT PT.
![File (7)](https://user-images.githubusercontent.com/21109275/114003973-1f059100-9856-11eb-909f-ab67af84b30d.jpg)
Can you add Portuguese translations? 

Thank you.

**Comment by jonathajones** [comment]
Thanks for reporting! will let you know when we have a resolution for this.

**Comment by jonathajones** [comment]
@SerggioC What version of the SDK are you integrating with?

**Comment by SerggioC** [comment]
@jonathajones version 0.44.0

**Comment by jonathajones** [comment]
Thanks! Will report back when we've identified a version that will include this fix :)

**Comment by SerggioC** [comment]
ok thanks!

**Comment by jonathajones** [comment]
Hey Serggio! We just released version `0.46.0` of the checkout SDK yesterday. Included in that release are the correct translation strings that were missing here. 

Thanks for reporting this to us!
