### ISSUE TITLE
Feature request: Refunds

### ISSUE THREAD

**Issue by SerggioC** [paypal/paypalcheckout-ios#42]
Hello, 

Is it possible that you can add a refund option to the SDK without server side integration?

Thank you.

**Comment by jonathajones** [comment]
Hey SerggioC - 
This is on our roadmap. I'll let you know here when we start work on providing the `refund` action through the SDK.

**Comment by SerggioC** [comment]
Hi jonathajones, 
That's great. Do you have any time frame for developing refund feature?
Thanks.

**Comment by jonathajones** [comment]
We're not sure where it fits on our roadmap just yet, but I'll update you when we have a time frame :)

**Comment by quintonpryce** [comment]
@SerggioC if you're looking for a way to do payouts, you can implement a web flow inside your app that logs the user in, from there you can scrape the access token from the url. With the access token (depending on what you configure in the paypal console) you can make a payout from your backend to the email & payer ID that is found within the access token.

**Comment by mpalanisamy-pkglobal** [comment]
@jonathajones , do you have any update on the refund feature from the SDK?

**Comment by jonathajones** [comment]
Hi @mpalanisamy-pkglobal - we do not; it's not a feature that we are planning on implementing in the near future.
