### ISSUE TITLE
📙 PayPalCreditButton not working

### ISSUE THREAD

**Issue by manoharsinghrawat-cedcoss** [paypal/paypalcheckout-ios#45]
I have added PaypalCreditButton but is not showing.

func button(_ button: PaymentButton, changedEligibilityStatus status: PaymentButtonEligibilityStatus) {
        print(status.rawValue)
        print(button.fundingSource)
    }

in this function i am getting status of ineligible. I am using US based paypal account so can anyone tell what's wrong in that?

**Comment by minhthenguyen** [comment]
Hi, 
Thanks for opening the issue.

Our payment buttons go through a funding eligibility check to determine if they are eligible, and we will hide them if they are ineligible. There are a lot of factors that are used to determine eligibility, and we will defer to ineligible if there is uncertainty.

We'll put a work item to our backlog to provide more fields that you can specify that can help with better determining eligibility of the buttons.

For now, you can use the `PayPalButton` (which will be eligible in most cases), tapping on `PayPalButton` will open our checkout paysheet, in which you will find Credit as one of the cards if it's eligible.
Please let me know if you still don't see Credit in the Paysheet :smile:

**Comment by manoharsinghrawat-cedcoss** [comment]
Hi @minhthenguyen Thanks for your quick answer. When I click the paypalbutton it opens a login page having a login button and one signup button. On clicking the signup button it opens a guest checkout page. So can we change the name or title of button 'Signup' to 'Pay by Credit Card' and if yes then how can we do that?

**Comment by minhthenguyen** [comment]
For now we haven't supported guest checkout in our SDK, that was why when you tapped 'Signup' in the login WebView, we redirect you to guest checkout on web.
If you have a PayPal account, after logging in, the login WebView will close and you will see our native checkout paysheet.

**Comment by jonathajones** [comment]
Closing this, as the original question is answered, and guest checkout is not yet natively supported.
