### ISSUE TITLE
[🐞] Bug Report : Paypal Dialog freezes searching for wallets

### ISSUE THREAD

**Issue by luisortizcisneros** [paypal/paypalcheckout-ios#47]
### 🔬 Minimal Reproduction
Describe steps to reproduce. 

I have this new app only with the PayPalCheckout pod installed, version is 0.51.0
I added the config object to the AppDelegate.swift file as the manual says with my own ClientID and returnUrl. 

This is the ViewController.swift file 

`import UIKit
import PayPalCheckout

class ViewController: UIViewController {

    @IBOutlet var mainView: UIView!
    @IBOutlet weak var containerView: UIView!
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
        let paymentButton = PayPalButton()
        view.addSubview(paymentButton)
        paymentButton.translatesAutoresizingMaskIntoConstraints = false
        paymentButton.leadingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.leadingAnchor,constant: 0).isActive = true
        paymentButton.trailingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.trailingAnchor,constant: 0).isActive = true
        paymentButton.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor,constant: 0).isActive = true
        paymentButton.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor,constant: 0).isActive = true
                    
                configurePayPalCheckout()
    }

    
    func configurePayPalCheckout() {
        func configurePayPalCheckout() {
                Checkout.setCreateOrderCallback { createOrderAction in
                    let amount = PurchaseUnit.Amount(currencyCode: .usd, value: "10.00")
                    let purchaseUnit = PurchaseUnit(amount: amount)
                    let order = OrderRequest(intent: .capture, purchaseUnits: [purchaseUnit])

                    createOrderAction.create(order: order)
                }

                Checkout.setOnApproveCallback { approval in
                     approval.actions.capture { (response, error) in
                        print("Order successfully captured: \(response?.data)")
                    }
                }

            }
    }
    
}`

### 😕 Actual Behavior
A clear and concise description of what is happening. Please debugger logs and error messages if applicable.

When I hit the paypal button, the log in screen for Paypal Pops up, I introduce sandbox email and password and then the dialog closes, with only the phrase "Pulling up your digital wallet

https://user-images.githubusercontent.com/77262341/120728625-f808bb80-c4a2-11eb-94ab-b295aa1c6fc5.mov

"
 
### 🤔 Expected Behavior

The dialog won't close and allow me to view the payment info, and proceed to pay.

### 🌍 Environment

- iOS version: - 14.4
- SDK version (`Checkout.version`): - 0.51.0

### ➕ Additional Context
Add any other context about the problem here. Screenshots or videos that show the issue are very helpful.

Here's a video of what I describe. I stays like that for about 30 minutes and then the dialog dissapears.

**Comment by jonathajones** [comment]
Hi @luisortizcisneros  - 
Thanks for the bug report. One way that you can help provide additional context is to add the `onError` callback, which would help us identify what is going wrong. 

Additionally - if you print out the contents of `State.correlationIDs`, is there a value?

**Comment by luisortizcisneros** [comment]
I added a print on each function and fixed an error in the previous viewcontroller, this is the new one and I still get the same result (screen stuck in the same place) if you need extra info, please ask for it, regards.

`
import UIKit
import PayPalCheckout

class ViewController: UIViewController {

    @IBOutlet var mainView: UIView!
    @IBOutlet weak var containerView: UIView!
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
        let paymentButton = PayPalButton()
        view.addSubview(paymentButton)
        paymentButton.translatesAutoresizingMaskIntoConstraints = false
        paymentButton.leadingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.leadingAnchor,constant: 0).isActive = true
        paymentButton.trailingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.trailingAnchor,constant: 0).isActive = true
        paymentButton.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor,constant: 0).isActive = true
        paymentButton.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor,constant: 0).isActive = true
        configurePayPalCheckout()
    }

    
    func configurePayPalCheckout() {
                Checkout.setCreateOrderCallback { createOrderAction in
                    print("State.correlationIDs: \(State.correlationIDs)")
                    let amount = PurchaseUnit.Amount(currencyCode: .usd, value: "10.00")
                    let purchaseUnit = PurchaseUnit(amount: amount)
                    let order = OrderRequest(intent: .capture, purchaseUnits: [purchaseUnit])

                    createOrderAction.create(order: order)
                }

                Checkout.setOnApproveCallback { approval in
                    print("State.correlationIDs: \(State.correlationIDs)")
                     approval.actions.capture { (response, error) in
                        print("Order successfully captured: \(response?.data)")
                    }
                }
            
            Checkout.setOnCancelCallback {
                // User has cancelled the payment experience
                print("State.correlationIDs: \(State.correlationIDs)")
                print("got to error callback")
            }
            
            Checkout.setOnErrorCallback { error in
                // Handle the error generated by the SDK
                print("got to error callback")
                print("State.correlationIDs: \(State.correlationIDs)")
                print(error)
            }

    }
    
}

`

These are the logs that I got

2021-06-03 20:50:28.573325-0500 paypalExample[45118:3360531] [] nw_protocol_get_quic_image_block_invoke dlopen libquic failed
State.correlationIDs: <PPCCorrelationIDs: 0x600002708ea0>
2021-06-03 20:50:35.192467-0500 paypalExample[45118:3360291] Random String = 9223372036923014957
2021-06-03 20:50:35.193244-0500 paypalExample[45118:3360291] Base 64 Encoded random Number = OTIyMzM3MjAzNjkyMzAxNDk1Nw==
2021-06-03 20:50:35.193581-0500 paypalExample[45118:3360291] Nonce = 2021-06-04T01:50:35ZOTIyMzM3MjAzNjkyMzAxNDk1Nw==
2021-06-03 20:50:35.196485-0500 paypalExample[45118:3360291] :::::Signature=====MEUCIGero8TCv+hXjIjcOROkPlSxTG0Y2m7rzaHJYIq9cokbAiEApQU0mcL+89CBX9b/ICDz1eMrXz7ZhvksElwTav2EBfU=
2021-06-03 20:50:35.196639-0500 paypalExample[45118:3360291] :::::Nonce=2021-06-04T01:50:35ZOTIyMzM3MjAzNjkyMzAxNDk1Nw==
2021-06-03 20:50:35.196747-0500 paypalExample[45118:3360291] :::::Signature=MEUCIGero8TCv+hXjIjcOROkPlSxTG0Y2m7rzaHJYIq9cokbAiEApQU0mcL+89CBX9b/ICDz1eMrXz7ZhvksElwTav2EBfU=
2021-06-03 20:50:35.196825-0500 paypalExample[45118:3360291] :::::PublicKey=MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE5UQ8NVZiqtP2lli4OwWoTz1+FH1Rbyl9rdcOkTIqN9MUALkwCItMpvHtpMiZ9u3B13Kwytw6iCrise+T6vcTvA==
2021-06-03 20:50:35.355290-0500 paypalExample[45118:3360465] [AXRuntimeCommon] Unknown client: paypalExample
2021-06-03 20:58:52.330408-0500 paypalExample[45118:3362212] [ServicesDaemonManager] interruptionHandler is called. -[FontServicesDaemonManager connection]_block_invoke

**Comment by jonathajones** [comment]
Thanks for the additional logs! In the developer portal (when you select your application from https://developer.paypal.com/developer/applications), did you allow `Login with PayPal`?  It'll look like this in the sandbox app settings:

<img width="586" alt="image" src="https://user-images.githubusercontent.com/74559931/120811595-c24eeb80-c511-11eb-9804-03314de6b6cd.png">

If that setting is enabled, we'll need to get a bit more information to assign this and debug from our side. If you could email me your sandbox client ID at `jonathajones@paypal.com`, that will help us track down what's happening.

**Comment by luisortizcisneros** [comment]
I sent you an email with the requested info, aditionally, the Log in with PayPal feature was check in the dashboard, thank you for your kind help.

**Comment by jonathajones** [comment]
Resolution was to fix a typo in the `returnUrl` provided to the SDK through the CheckoutConfig object.

**Comment by Pelican43** [comment]
Hi,

Same here. How did you resolve the issue ? 

Best regards.

**Comment by Pelican43** [comment]
> I sent you an email with the requested info, aditionally, the Log in with PayPal feature was check in the dashboard, thank you for your kind help.



> ### 🐞 Describe the Bug
> A clear and concise description of what the bug is.
> 
> ### 🔬 Minimal Reproduction
> Describe steps to reproduce.
> 
> I have this new app only with the PayPalCheckout pod installed, version is 0.51.0
> I added the config object to the AppDelegate.swift file as the manual says with my own ClientID and returnUrl.
> 
> This is the ViewController.swift file
> 
> `import UIKit
> import PayPalCheckout
> 
> class ViewController: UIViewController {
> 
> ```
> @IBOutlet var mainView: UIView!
> @IBOutlet weak var containerView: UIView!
> override func viewDidLoad() {
>     super.viewDidLoad()
>     // Do any additional setup after loading the view.
>     let paymentButton = PayPalButton()
>     view.addSubview(paymentButton)
>     paymentButton.translatesAutoresizingMaskIntoConstraints = false
>     paymentButton.leadingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.leadingAnchor,constant: 0).isActive = true
>     paymentButton.trailingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.trailingAnchor,constant: 0).isActive = true
>     paymentButton.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor,constant: 0).isActive = true
>     paymentButton.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor,constant: 0).isActive = true
>                 
>             configurePayPalCheckout()
> }
> 
> 
> func configurePayPalCheckout() {
>     func configurePayPalCheckout() {
>             Checkout.setCreateOrderCallback { createOrderAction in
>                 let amount = PurchaseUnit.Amount(currencyCode: .usd, value: "10.00")
>                 let purchaseUnit = PurchaseUnit(amount: amount)
>                 let order = OrderRequest(intent: .capture, purchaseUnits: [purchaseUnit])
> 
>                 createOrderAction.create(order: order)
>             }
> 
>             Checkout.setOnApproveCallback { approval in
>                  approval.actions.capture { (response, error) in
>                     print("Order successfully captured: \(response?.data)")
>                 }
>             }
> 
>         }
> }
> ```
> 
> }`
> 
> ### 😕 Actual Behavior
> A clear and concise description of what is happening. Please debugger logs and error messages if applicable.
> 
> When I hit the paypal button, the log in screen for Paypal Pops up, I introduce sandbox email and password and then the dialog closes, with only the phrase "Pulling up your digital wallet
> 
>  screenBug.mov 
> "
> 
> ### 🤔 Expected Behavior
> A clear and concise description of what you expected to happen.
> 
> The dialog won't close and allow me to view the payment info, and proceed to pay.
> 
> ### 🌍 Environment
> * iOS version: - 14.4
> * SDK version (`Checkout.version`): - 0.51.0
> 
> ### ➕ Additional Context
> Add any other context about the problem here. Screenshots or videos that show the issue are very helpful.
> 
> Here's a video of what I describe. I stays like that for about 30 minutes and then the dialog dissapears.

Hi,

Same here. How did you resolve the issue ?

Best regards.

**Comment by jonathajones** [comment]
HI @Pelican43  - 
Resolution was to fix a typo in the returnUrl provided to the SDK through the CheckoutConfig object. Double check your configuration to make sure the return URL is exactly correct as defined in your developer dashboard.

**Comment by Pelican43** [comment]
> Hi @Pelican43 -
> Resolution was to fix a typo in the returnUrl provided to the SDK through the CheckoutConfig object. Double check your configuration to make sure the return URL is exactly correct as defined in your developer dashboard.

Hi Jonathanjones,

Thank's for your feedback.
For the returnUrl: I put the bundle identifier of my app suffixed with "://paypalpay". (as the Checkout Native SDK documentation said).  We can see it on joined pics. 
For information, I am in Production(live) mode.

![code_paypal_client](https://user-images.githubusercontent.com/20114139/123472121-086e0b00-d5f7-11eb-80be-ef792ab81235.jpg)
![code_paypal_dashboard](https://user-images.githubusercontent.com/20114139/123472123-099f3800-d5f7-11eb-9497-4d67d991feec.jpg)

**Comment by jonathajones** [comment]
Got it -  try making the entire return URL lowercase, and set the return url in the dashboard the same way. Let me know if this helps address the issue!

**Comment by Pelican43** [comment]
> Got it - try making the entire return URL lowercase, and set the return url in the dashboard the same way. Let me know if this helps address the issue!

You're the best Jonathajones. It's  working in making the returnUrl in lowercase. I hope this feed helps other ones.
