### ISSUE TITLE
[🐞] Bug Report: Paypal presenting Login Window twice on click Paypal SDK Button

### ISSUE THREAD

**Issue by ashokksolanki** [paypal/paypalcheckout-ios#48]
### 🔬 Minimal Reproduction
Describe steps to reproduce. 
I have installed PayPalCheckout pod, version is 0.51.0
I added the config object on init of PaypalView to the PaypalView.swift file as the manual says with my own ClientID and returnUrl. After configuration setup, below are delegates method implementation code for reference:

`extension GSPaypalView : PaymentButtonDelegate {
    
    func onButtonStart(_ button: PaymentButton) {
        // Invoked when the button is tapped, before the checkout process begins.
        print("onButtonStart")
        triggerPayPalCheckout()
    }
    //
    func onButtonFinish(_ button: PaymentButton) {
        // Invoked when the checkout process has finished
        print("onButtonFinish")
    }
    
    func button(_ button: PaymentButton, changedEligibilityStatus status: PaymentButtonEligibilityStatus) {
        // Invoked when the eligibility status of the button has changed
        print("changedEligibilityStatus")
    }
    
    func triggerPayPalCheckout() {
        
        Checkout.start(
            createOrder: { createOrderAction in
                
                let amount = PurchaseUnit.Amount(currencyCode: .usd, value: "5.00")
                let purchaseUnit = PurchaseUnit(amount: amount)
                let order = OrderRequest(intent: .capture, purchaseUnits: [purchaseUnit])
                
                createOrderAction.create(order: order)
                
            }, onApprove: { approval in
                
                approval.actions.capture { (response, error) in
                    if let orderInfo = response?.data {
                        print("Order successfully captured id: \(orderInfo.id)")
                        print("Order successfully captured status: \(orderInfo.status)")
                        print("Order successfully captured orderData: \(orderInfo.orderData)")
                    } else {
                        print("Order success Error \(error?.localizedDescription ?? "Error")")
                    }
                }
                
            }, onCancel: {
                
                // Optionally use this closure to respond to the user canceling the paysheet
                print("Order Cancelled")
            }, onError: { error in
                
                // Optionally use this closure to respond to the user experiencing an error in
                // the payment experience
                print("Order Error: \(error.reason)")
            }
        )
    }    
}
`

### 😕 Actual Behavior
A clear and concise description of what is happening. Please debugger logs and error messages if applicable.

When I hit the PayPal button, the login screen for Paypal Pops up twice, I introduce sandbox email and password and then the dialog closes, and one for the controller is present there with the same login window. I have to enter the login credential again then only I can proceed with the transaction.

https://user-images.githubusercontent.com/21368118/120809203-74fd6900-c567-11eb-9cef-cda13c88881a.mov

If I click on cancel after providing credential in the first popup window then it will cancel the order. 
So the issue is Login is asked twice.

### 🤔 Expected Behavior
The login window should appear only one time.

### 🌍 Environment

- iOS version: - 14.1
- SDK version (`Checkout.version`): - 0.51.0

### ➕ Additional Context
Add any other context about the problem here. Screenshots or videos that show the issue are very helpful.
Attached video for reference.

**Comment by jonathajones** [comment]
Hi @ashokksolanki ! 

Thanks for the bug report. Could you provide any tokens that are associated with this experience? 
An EC token (you could get this from the optional closure on the `createOrderAction.create(order: order)` function), as well as the identifiers stored in `State.correlationIDs` would be helpful.

**Comment by ashokksolanki** [comment]
Hi @jonathajones ,

Thanks for quick response. This is heppening for each order when I click on paypal checkout button. I don't understood exactly how to achieve this information. But I tried
`
createOrderAction.create(order: order) { (response) in
                    print("Order resposne ", response)
                }
`
and I got response string as '07V60815JS008072J'
in proxy I could see this for above token "correlationId": "5f644a9cd26f2"

Note: I could see `createOrderAction.create` completion is called two times and two different token is created.

I hope it will helpful. Let me know if anything else is required from myside.

Thanks

**Comment by jaxdesmarais** [comment]
Hello @ashokksolanki -

Taking a look at your code, in your `triggerPayPalCheckout` function you are currently calling `Checkout.start`. With the Payment Buttons `Checkout.start` is called automatically via the SDK. This is resulting in the duplication of create order completion calls. Instead, you will want to use the `Checkout.set___Callback` helper functions like so in your `triggerPayPalCheckout` funtion:
```
Checkout.setCreateOrderCallback { createOrderAction in
      
  let amount = PurchaseUnit.Amount(currencyCode: .usd, value: "5.00")
  let purchaseUnit = PurchaseUnit(amount: amount)
  let order = OrderRequest(intent: .capture, purchaseUnits: [purchaseUnit])
      
  createOrderAction.create(order: order) { response in
    print("Order response ", response)
  }
}
      
Checkout.setOnApproveCallback { approval in
  approval.actions.capture { (response, error) in
    if let orderInfo = response?.data {
      print("Order successfully captured id: \(orderInfo.id)")
      print("Order successfully captured status: \(orderInfo.status)")
      print("Order successfully captured orderData: \(orderInfo.orderData)")
    } 
    else {
      print("Order success Error \(error?.localizedDescription ?? "Error")")
    }
  }
}
    
Checkout.setOnCancelCallback {        
  print("Checkout cancelled")      
}

Checkout.setOnErrorCallback {  errorInfo in        
  print("Checkout failed with error info \(errorInfo.error.localizedDescription)")  
}
```
Please do let us know if you continue running into issues after making the above updates.

**Comment by ashokksolanki** [comment]
Thanks, @jaxdesmarais, this solution worked for me. 

But as per your recommendation, `setCreateOrderCallback` needs to be set outside of `onButtonStart`. As per our requirement, the Paypal button is shown to the user on the `Cart` page where the user can update cart items in that case order will also be impacted and we need to update that. So either we have to trigger an event or can you suggest a better approach to achieve this?

**Comment by jaxdesmarais** [comment]
Happy to hear the solution is working @ashokksolanki. I don't want to make too many assumptions about your app architecture, but am going to assume the extension of `GSPaypalView` is a `UIView`. If so, you can call this function in the `init` of your main `GSPaypalView` like so:
```
  override init(frame: CGRect) {
    super.init(frame: frame)
    triggerPayPalCheckout()
  }
  ```
With the above method, you will need to move the entire `triggerPayPalCheckout` function to the main `UIView` instead of the extension and ensure it's called after setting the config for PayPal Checkout. You will need to move this function to your main view class instead of the extension because you [cannot override existing functionality in an extension](https://docs.swift.org/swift-book/LanguageGuide/Extensions.html). Again, you many need to adapt the above according to how your application is architected. Another option as you suggested is to use an eventing system to achieve this depending on if the above does not work for how your app is currently set up.

**Comment by ashokksolanki** [comment]
Thanks @jaxdesmarais,
