### ISSUE TITLE
[🐞] Stuck on "Pulling up your digital wallet"

### ISSUE THREAD

**Issue by mannycalavera27** [paypal/paypalcheckout-ios#49]
### 🐞 Describe the Bug
After logging in, the app is stuck on "Pulling up your digital wallet"

### 🔬 Minimal Reproduction
Tap on PayPalButton -> Login using PayPal credentials

### 😕 Actual Behavior
The app is stuck on "Pulling up your digital wallet", no log in the console

### 🤔 Expected Behavior
Continue with the next step of the payment process

### 🌍 Environment

- iOS version: 14
- SDK version (`Checkout.version`): - 0.55.0

### ➕ Additional Context
Add any other context about the problem here. Screenshots or videos that show the issue are very helpful.
![Simulator Screen Shot - iPhone 12 Pro - 2021-06-18 at 10 13 12](https://user-images.githubusercontent.com/60178622/122549187-7f713580-d032-11eb-894f-69a7ea22e95d.png)

**Comment by jonathajones** [comment]
Hi Tiziano -  
Thanks for opening up an issue!

Some initial things to check:
- Does your return URL that you recorded in the developer console match what you provided to the config? 
- Do you get past the login step?
- Are you using the right identifiers for the environment you're in? (ie sandbox tokens & clientID for the sandbox environment)

**Comment by mannycalavera27** [comment]
Hi Jonatha,
thanks for replying quickly.

- Return URL is ok
- Login step passed
- Token and clientID are from sandbox environment, the one I'm testing

**Comment by jonathajones** [comment]
Great. A couple things:
1. Could you post what your `createOrder` step looks like? 
2. Double check the return URL, as the value here is case sensitive. 
Thanks,
Jon

**Comment by mannycalavera27** [comment]
1. Here is my code (from viewDidLoad):

```
let paymentButton = PayPalButton()
...
...
Checkout.setCreateOrderCallback { createOrderAction in
            let amount = PurchaseUnit.Amount(currencyCode: .usd, value: "10.00")
            let purchaseUnit = PurchaseUnit(amount: amount)
            let order = OrderRequest(intent: .capture, purchaseUnits: [purchaseUnit])
            
            createOrderAction.create(order: order)
        }

Checkout.setOnApproveCallback { approval in
            approval.actions.capture { (response, error) in
                print("Order successfully captured: \(String(describing: response?.data))")
            }
        }

```

2. Double-checked, everything is ok

**Comment by jonathajones** [comment]
Gotcha, thanks for sending this on. Could you email your sandbox client ID to me at `jonathajones@paypal.com`? That'll help us to see if there's something else going on behind the scenes. 

Thanks!

**Comment by mannycalavera27** [comment]
Just sent, thanks for the support

**Comment by jonathajones** [comment]
Resolution was to use a `returnURL` value that did not include capital letters. Will need to add this to our documentation around `returnURL`s in the future.

**Comment by AndrexOfficial** [comment]
@jonathajones Hello, I'm having the same issue.
It works only if I start the Paypal checkout from a viewController, If I use a payment manager it stucks to "Pulling up your digital wallet" or it presents a white view with no labels, images or buttons

**Comment by jonathajones** [comment]
Hi @AndrexOfficial  - 
The resolution in this case was an issue with the return URL. 
Two suggestions: 
1. Check that the return URL being provided in the developer dashboard exactly matches what you are supplying in your config
2. We've seen some issues with capital letters causing hangups in our auth SDK. Make sure your returnURL in both the developer dashboard and the config are lowercased.

Let me know if you're still seeing this behavior after trying those.

Thanks!

**Comment by AndrexOfficial** [comment]
Here is how it presents the view

![pp-error](https://user-images.githubusercontent.com/1239878/124147528-11475c80-da8f-11eb-9b6c-a03b6f937d2d.jpg)

**Comment by jonathajones** [comment]
Hi @AndrexOfficial  - 
That looks like a different issue. Please open a new ticket with a description and reproduction steps.

Thanks!

**Comment by AndrexOfficial** [comment]
It is partially a different issue, because it gets stuck on "Pulling up your digital wallet" also.
It depends from where you initialize the SDK

I'll open a new ticket.
Thanks

**Comment by JigneshPal** [comment]
> Hi @AndrexOfficial -
> The resolution in this case was an issue with the `returnUrl`.
> Two suggestions:
> 
> 1. Check that the `returnUrl` being provided in the developer dashboard exactly matches what you are supplying in your config
> 2. We've seen some issues with capital letters in the `returnUrl` causing hangups in our auth SDK. Make sure your `returnUrl` in both the developer dashboard and the config are lowercased.
> 
> Let me know if you're still seeing this behavior after trying those steps.
> 
> Thanks!

Hello @jonathajones,

As mentioned in document we need to use bundle id append with ://paypalpay, in my bundle id there is some capital letters and if i use small in return URL, is this problematic?

My returnURL from dashboard and config both are same in lowercase but my app id contains some capitals.

![Screenshot 2021-08-13 at 12 43 42 PM](https://user-images.githubusercontent.com/88715593/129319061-ad9f6d5b-2dc4-4220-9804-cfc6c289621a.png)

And i am getting bellow fail error from response.
![Screenshot 2021-08-13 at 12 45 45 PM](https://user-images.githubusercontent.com/88715593/129320255-91e24a86-8169-4116-b28d-7c2bc9f8c020.png)
