### ISSUE TITLE
Integration with Swift

### ISSUE THREAD

**Issue by rakesh1504** [paypal/paypalcheckout-ios#5]
Do you have any example for swift setup?

**Comment by edvinassabaliauskas** [comment]
Hi, when can we expect it to be updated?

**Comment by dmikey** [comment]
Please find the missing signatures added to the current pod, thanks!

**Comment by taimoorsuleman** [comment]
Hi, Please share #import "" command. which is used in bridging header.
i want to user it in swift project.
