### ISSUE TITLE
Include arm64 arch for Apple M1

### ISSUE THREAD

**Issue by PeqNP** [paypal/paypalcheckout-ios#50]
### Describe Your Issue

I would like to to support running our (Nordstrom) app on the simulator natively on Apple M1 silicon. I saw that your pod spec excludes the arm64 arch. When do you plan to support M1?

**Comment by jonathajones** [comment]
Hi @PeqNP  - We're in progress updating our dependencies to be able to support arm64 on simulators. I'll let you know when we have an ETA on a release with this included!

**Comment by PeqNP** [comment]
That's great. Thank you so much!

**Comment by jonathajones** [comment]
Hi @PeqNP -
Do you have M1 machines that you use in development or in the CI process? We're looking for someone to test the next build that supports arm64 for iOS simulators. Is that something that you would be able to do / interested in?

**Comment by PeqNP** [comment]
Yes. There are two devs here that have M1 machines. I would be happy to test it!

**Comment by jonathajones** [comment]
That's great - would you email me at `jonathajones@paypal.com`? I'll let you know when the SDK is ready for beta testing. 

Thanks!

**Comment by jonathajones** [comment]
Support for M1 simulators has been added in release 0.64.0 - you can find it here: https://github.com/paypal/paypalcheckout-ios/releases/tag/0.64.0

**Comment by PeqNP** [comment]
Thank you so much, Jon!
