### ISSUE TITLE
how to use the SDK make a express-checkout

### ISSUE THREAD

**Issue by loveuqian** [paypal/paypalcheckout-ios#52]
can not get a `payment_id` and `payer_id` in `authorizeOnComplete:`

**Comment by jonathajones** [comment]
Hi @loveuqian  - can you use the templates to provide us more information? This is not enough to go on to help triage your issue.

**Comment by vasylnahuliak** [comment]
The same problem. In `setOnApproveCallback` get `payerID` is empty string, `paymentID` is `nil`

`
import PayPalCheckout

@objc(Paypal)
class Paypal: NSObject {
    @objc func checkout(
        _
            clientID: String,
        returnURL: String,
        useSandbox: Bool,
        orderID: String,
        resolver: @escaping RCTPromiseResolveBlock,
        rejecter: @escaping RCTPromiseRejectBlock
    ) -> Void {
        let environment = useSandbox ? Environment.sandbox : Environment.live
        let config = CheckoutConfig(
            clientID: clientID,
            returnUrl: returnURL,
            environment: environment
        )
        
        Checkout.set(config: config)
        
        Checkout.setCreateOrderCallback { createOrderActions in
            createOrderActions.set(billingAgreementToken: orderID)
        }
        
        Checkout.setOnApproveCallback { approval in
            resolver([
                "ecToken": approval.data.ecToken,
                "payerID": approval.data.payerID,
                "paymentID": approval.data.paymentID
            ])
        }
        
        Checkout.setOnErrorCallback { error in
            rejecter(error.reason, error.description, nil)
        }
        
        DispatchQueue.main.async {
            Checkout.start()
        }
        
    }
}
`

FYI: using for create React Native plugin

**Comment by jonathajones** [comment]
Been open for a bit without a response, and we need more information to help debug. Please open a new issue using our issue templates to help us improve the SDK. Thanks!
