### ISSUE TITLE
[🐞] Bug Report: Cannot find Swift declaration for this class

### ISSUE THREAD

**Issue by srikanth-vm** [paypal/paypalcheckout-ios#53]
When building, I am getting below error:
```
'CheckoutConfig' is unavailable: cannot find Swift declaration for this class
```

- iOS version: - 13.x, 14.x
- SDK version (`0.55.0`): -

XCFramework contains only `x86_64` architectures, could this be an issue ?

**Comment by jonathajones** [comment]
Hi @srikanth-vm ! Could you Use one of the issue templates to provide a bit more clarity here? Without having more information about what your interface looks like. 

Other pieces of information we'll need: 
- Are you working from an M1 machine?
- If not, you could try adding `arm64` to the `Excluded Architectures` field for simulators

**Comment by Dhruvpargai** [comment]
@srikanth-vm I fixed this by updating my Cocoapods to the latest version(1.10.1). I think the problem was that my older Cocoapods(v1.8.3) wasn't able to build and/or import xcframework based pods

**Comment by jonathajones** [comment]
This should be resolved using the solution posted by @Dhruvpargai - additionally, we have added `arm64` support for M1 simulator architecture with latest release (https://github.com/paypal/paypalcheckout-ios/releases/tag/0.64.0).

**Comment by cythb** [comment]
I have this problem too. My pod's version is 1.11.2.

**Comment by cythb** [comment]
@srikanth-vm Have you solved your problem?

**Comment by jonathajones** [comment]
@cythb  - If the issue you're seeing is related to concurrency -  try downgrading to version `0.77.0`. Our next minor version will revert the compiled swift language version, which will resolve the issue.
