### ISSUE TITLE
[🐞] Bug Report: payerID is empty string, paymentID is nil

### ISSUE THREAD

**Issue by vasylnahuliak** [paypal/paypalcheckout-ios#54]
### 🐞 Describe the Bug
setOnApproveCallback return approval.data with `payerID` is empty string, `paymentID` is `nil`

### 🔬 Minimal Reproduction
Programmatically start the SDK https://developer.paypal.com/docs/business/native-checkout/ios/programmatically-start-sdk/

```
import PayPalCheckout

@objc(Paypal)
class Paypal: NSObject {
    @objc func checkout(
        _
            clientID: String,
        returnURL: String,
        useSandbox: Bool,
        orderID: String,
        resolver: @escaping RCTPromiseResolveBlock,
        rejecter: @escaping RCTPromiseRejectBlock
    ) -> Void {
        let environment = useSandbox ? Environment.sandbox : Environment.live
        let config = CheckoutConfig(
            clientID: clientID,
            returnUrl: returnURL,
            environment: environment
        )
        
        Checkout.set(config: config)
        
        Checkout.setCreateOrderCallback { createOrderActions in
            createOrderActions.set(billingAgreementToken: orderID)
        }
        
        Checkout.setOnApproveCallback { approval in
            resolver([
                "ecToken": approval.data.ecToken,
                "payerID": approval.data.payerID,
                "paymentID": approval.data.paymentID
            ])
        }
        
        Checkout.setOnErrorCallback { error in
            rejecter(error.reason, error.description, nil)
        }
        
        DispatchQueue.main.async {
            Checkout.start()
        }
        
    }
}

```

### 😕 Actual Behavior
 `payerID` is empty string, `paymentID` is `nil`

### 🤔 Expected Behavior
`payerID` and `paymentID` must be in `setOnApproveCallback` response

### 🌍 Environment

- iOS version: - 14.5
- SDK version (`Checkout.version`): -0.55.0

### ➕ Additional Context
Create for React Native bridge, checkout function called from JS

**Comment by minhthenguyen** [comment]
Hi @vasylnahuliak 
Thank you for reporting this issue to us, we're working on a fix for this now. We'll let you know when to expect it in a release.

**Comment by minhthenguyen** [comment]
@vasylnahuliak Sorry for the late response, I'm following up with our team on this fix and will let you know as soon as I get more info.

**Comment by minhthenguyen** [comment]
Hi @vasylnahuliak 
Sorry for the long delay, the fix for this has now been deployed.
The `paymentID` doesn't apply for our billing agreement flow so it won't be available.
But the `payerID` has been added. Please check and let us know if there's any further issue.
Thank you.

**Comment by minhthenguyen** [comment]
Closing this issue as the bug has been fixed.
If you encounter further issues/questions down the line please feel free to open another.
