### ISSUE TITLE
Pulling up your digital wallet

### ISSUE THREAD

**Issue by JigneshPal** [paypal/paypalcheckout-ios#56]
I am using latest SDK 0.64.0

Click on payment button and login confirmation alert is showing that is proper and on click of continue it is presenting login in safari which is perfect.

But after successfully login safari will dismiss and just showing "Pulling up your digital wallet" as below.
And didn't get anything.  

Please advise us.

![Screen Shot 2021-08-10 at 4 03 51 PM](https://user-images.githubusercontent.com/88715593/128853052-bfa55072-66ff-4fee-95f7-a1b314954195.png)

**Comment by jonathajones** [comment]
@JigneshPal  Thanks for opening an issue. A couple things to try:

1.  Ensure that the client ID being used by the SDK matches the one in your developer profile, and the return URL being sent to the SDK also exactly matches the return URL as listed in the developer console.
2. Does your return URL contain any special or uppercase characters? If so, make those lowercase. 

Let me know if this helps you! 
Jon

**Comment by JigneshPal** [comment]
Thank you @jonathajones,

There was uppercase letters in return url.

After your solution now it is working.
