### ISSUE TITLE
ReturnURL Question

### ISSUE THREAD

**Issue by JigneshPal** [paypal/paypalcheckout-ios#58]
> Hi @AndrexOfficial -
> The resolution in this case was an issue with the `returnUrl`.
> Two suggestions:
> 
> 1. Check that the `returnUrl` being provided in the developer dashboard exactly matches what you are supplying in your config
> 2. We've seen some issues with capital letters in the `returnUrl` causing hangups in our auth SDK. Make sure your `returnUrl` in both the developer dashboard and the config are lowercased.
> 
> Let me know if you're still seeing this behavior after trying those steps.
> 
> Thanks!

Hello @jonathajones,

As mentioned in document we need to use bundle id append with ://paypalpay, in my bundle id there is some capital letters and if i use small in return URL, is this problematic?

My returnURL from dashboard and config both are same in lowercase but my app id contains some capitals.

![Screenshot 2021-08-13 at 12 43 42 PM](https://user-images.githubusercontent.com/88715593/129319061-ad9f6d5b-2dc4-4220-9804-cfc6c289621a.png)

And i am getting bellow fail error from response.
![Screenshot 2021-08-13 at 12 45 45 PM](https://user-images.githubusercontent.com/88715593/129320255-91e24a86-8169-4116-b28d-7c2bc9f8c020.png)

**Comment by jonathajones** [comment]
Hi @JigneshPal - 
Thanks for opening an issue. The lack of a return URL in the `ApprovalData` does not necessarily indicate a failure.
The SDK uses the supplied `returnURL` as part of the authentication process. 

The format `<bundle_identifier>://paypalpay` is convention, and is more consequential on Android than when using the iOS SDK, so stripping it of special characters and using lowercases should not be an issue. 

Unless you're noticing behavior issues beyond the `returnURL` value of the `ApprovalData` being nil, it seems the SDK is behaving as expected
