### ISSUE TITLE
[🐞] Bug Report - After paypal login, it's keeps loading...

### ISSUE THREAD

**Issue by nkollu** [paypal/paypalcheckout-ios#60]
### 🐞 Describe the Bug
After PayPal login, it's loading forever, I am unable to proceed.

![Simulator Screen Shot - iPhone 11 Pro Max - 2021-08-31 at 12 47 59](https://user-images.githubusercontent.com/42729144/131460514-237cbb70-e4a6-4b54-aae3-1fd198024ef1.png)

### ➕ Additional Context
Add any other context about the problem here. Screenshots or videos that show the issue are very helpful.

**Comment by jonathajones** [comment]
Thanks for the bug report, @nkollu - a couple things you might try.
1. Ensure the `returnUrl` being passed to the SDK matches one that you specify in your developer console.
2. Strip the returnUrl of special characters (besides `.` and `://`) and make it lowercase - both in your developer console and in your application.

Let me know if this works for you!
Thanks
Jon

**Comment by nkollu** [comment]
Hi @jonathajones, bundle id is cap's in paypal, after changed to small it is working. But have got another issue

**Comment by jonathajones** [comment]
Great - thanks for opening a separate issue. Closing this.
