### ISSUE TITLE
[🚀] Feature Request

### ISSUE THREAD

**Issue by stefanoandreetta** [paypal/paypalcheckout-ios#64]
### 🚀 Feature Request

Add (or move) the Checkout Cancel callback at the end Checkout view closing animation.

### Motivation

I wanted to show an alert when checkout operation is canceled.
Now I'm using **Checkout.setOnCancelCallback { }**, but if I insert an alert inside the completion handler, it tries to show the alert controller when the Checkout view is dismissing, and this causes the "Attempt to present UIAlertController while a presentation is in progress".

Now I'm using this code as workaround:

```
Checkout.setOnCancelCallback {
    let seconds = 2.0
    DispatchQueue.main.asyncAfter(deadline: .now() + seconds) {
        // code to show alert
    }
}

```
Could it be possibile?

**Comment by jonathajones** [comment]
Hi @stefanoandreetta - 
Thanks for opening the feature request! This is a known issue that is in our backlog. I'll let you know when we have the chance to prioritize it for a specific release. In the meantime, your workaround is a good way to go to issues when triggering navigation from the approve / cancel / error blocks.

**Comment by devchristina** [comment]
Hi @stefanoandreetta - Unfortunately, this request has not made it to the backlog. Because of this, we will close this request as not planned.
