### ISSUE TITLE
[🐞] how to call up the payment page

### ISSUE THREAD

**Issue by w2311284** [paypal/paypalcheckout-ios#66]
### 🐞 Describe the Bug
Unable to call up the payment page after login

### 😕 Actual Behavior
View the video

### 🤔 Expected Behavior
tuning up the payment

### 🌍 Environment

- iOS version: - 14.7
- SDK version (`0.55.0`): -

### ➕ Additional Context
Add any other context about the problem here. Screenshots or videos that show the issue are very helpful.

**Comment by w2311284** [comment]
https://user-images.githubusercontent.com/12790219/134794135-85a637c3-75e4-4c6c-8d35-a42df3d963a6.MP4

**Comment by jaxdesmarais** [comment]
Hello @w2311284 -

A couple things to try:

1. Ensure that the client ID being used by the SDK matches the one in your developer profile, and the return URL being sent to the SDK also exactly matches the return URL as listed in the developer console.
2. Ensure your return url is **entirely lowercase**, both in the developer console and as passed to the SDK.

Please let me know if you continue to run into issues after testing the above.

**Comment by gokulnair2001** [comment]
#67  same issue, I have tried the above mentioned things, still its not working.

**Comment by w2311284** [comment]
> 你好@w2311284 -
> 
> 有几件事可以尝试：
> 
> 1. 确保 SDK 使用的客户端 ID 与您的开发者配置文件中的客户端 ID 匹配，并且发送到 SDK 的返回 URL 也与开发者控制台中列出的返回 URL 完全匹配。
> 2. 确保您的返回 url在开发者控制台中和传递给 SDK 时**完全小写**。
> 
> 如果您在测试上述内容后仍然遇到问题，请告诉我。

Thank you very much，Because the returned url contains uppercase letters。But your documentation doesn't make that clear，And Bundle  identifer contains uppercase letters

**Comment by w2311284** [comment]
Our Bundle identifier contains capital letters. In this case, how to fill in returnUrl? Can returnUrl be inconsistent with the Bundle ID?

**Comment by gokulnair2001** [comment]
> Our Bundle identifier contains capital letters. In this case, how to fill in returnUrl? Can returnUrl be inconsistent with the Bundle ID?

same question @jaxdesmarais

**Comment by gokulnair2001** [comment]
can you have a look at #67

**Comment by w2311284** [comment]
> 你好@w2311284和@gokulnair2001 -
> 
> 您的返回 URL 不需要包含您的包 ID。更重要的是`CheckoutConfig`对象中的返回 URL与开发人员门户中的匹配。例如，我只能使用应用程序包 ID`com.jax.MyTestPayPalCheckoutApp`和返回 URL 进行测试`tacocats://paypalpay`。从那里，我的`CheckoutConfig`和开发者门户中的返回 URL匹配，并且 SDK 按预期运行。
> 
> 此外，我们正在努力更新文档以反映这种小写的要求。我们感谢反馈。

I try to using ruturnUrl different from the Bundle ID but the payment failed, both iOS and Android, and the payment was fine when the returnUrl was the same as Bundle ID

**Comment by w2311284** [comment]
I have no more questions, thanks

**Comment by jaxdesmarais** [comment]
> I try to using ruturnUrl different from the Bundle ID but the payment failed, both iOS and Android, and the payment was fine when the returnUrl was the same as Bundle ID

@w2311284 It typically takes up to 3 hours for the changed to the return URL to propagate. That said, based on your most recent reply, it sounds like you were able to resolve your issue. I'll be closing out this issue, but if you have any follow up questions, please feel free to re-open this issue or open up a new issue if it's unrelated to the above.
