### ISSUE TITLE
[🐞] The operation couldn’t be completed. (OrderActionError error 1.)

### ISSUE THREAD

**Issue by gokulnair2001** [paypal/paypalcheckout-ios#67]
### 🐞 Describe the Bug
The operation couldn’t be completed. (OrderActionError error 1.)
When I am trying to check out it's giving me this error.

### 🔬 Minimal Reproduction
```swift
 func configurePaypal() {
        let config = CheckoutConfig(
            clientID: keys.valueOf.paymentGatewayToken,
            returnUrl: "url",
            environment: .sandbox
        )
        
        Checkout.set(config: config)
    }


func triggerPayPalCheckout(cost: String) {
        Checkout.start(
            createOrder: { createOrderAction in

                let amount = PurchaseUnit.Amount(currencyCode: .usd, value: cost)
                let purchaseUnit = PurchaseUnit(amount: amount)
                let order = OrderRequest(intent: .capture, purchaseUnits: [purchaseUnit])

                createOrderAction.create(order: order)

            }, onApprove: { approval in

                approval.actions.capture { (response, error) in
                    print("Order successfully captured: \(response?.data)")
                  
                    print("neW: \(error?.localizedDescription)")
                }

            }, onCancel: {
                
                // Optionally use this closure to respond to the user canceling the paysheet

            }, onError: { error in
                print("error is: \(error.reason)")
                print(error.correlationIDs)
                print(error.payToken)
                // Optionally use this closure to respond to the user experiencing an error in
                // the payment experience

            }
        )
    }
```

### 😕 Actual Behavior
<PPCCorrelationIDs: 0x2813be9e0>
The operation couldn’t be completed. (OrderActionError error 1.)

### 🤔 Expected Behavior
I need to make payment through Paypal

### 🌍 Environment

- iOS version: - 15.0
- SDK version (`Checkout.version`): -

### ➕ Additional Context
-

**Comment by gokulnair2001** [comment]
my returnURL follows all the criteria which you have mentioned, it's the same on the developer console and config method

**Comment by jaxdesmarais** [comment]
Hello @gokulnair2001 -

Can you please provide the following so we can troubleshoot further:
1. The raw order you are passing into `createOrderAction.create(order: order)`. Specifically looking to ensure the `cost` you are passing into your amount object is of the expected format, but the whole object will ensure that we are testing passing this in the same way.
2. The correlation ID being returned in the `<PPCCorrelationIDs: 0x2813be9e0>` object

I look forward to hearing back.

**Comment by gokulnair2001** [comment]
So sorry, actually I was passing a cost with a single zero after the decimal (i.e 99.0), but now I had made the correction still it's giving me the below-mentioned error

The operation couldn’t be completed. (OrderActionError error 1.)
<PPCCorrelationIDs: 0x6000007c5180>

**Comment by jaxdesmarais** [comment]
Hello @gokulnair2001 -

Thanks for sending over those details. Are you able to check the following:
1. That `keys.valueOf.paymentGatewayToken` is being passed into the `config` object as a string. To do this you can add a breakpoint at `Checkout.set(config: config)` and print out the `config` object in the debug console. Ensure that the value for `clientID` and the `returnUrl` value in that object matches the client ID and return URL in your PayPal developer console.
2. Confirm that you have updated to the latest SDK version (0.70.0).
3. In your `onError` callback, print the value for `error.correlationIDs.lsatUpgradeDebugID`.

**Comment by gokulnair2001** [comment]
Hey @jaxdesmarais , I have solved the issue, thank you for your constant help it really helped me to solve the issue.

I have a small doubt, can we get the payment/transaction/checkout time once the process is done through Paypal?
Like i need the payment completion timing, once the payment is done i need at which time it was done, is their any parameter for that in the ```response```

**Comment by jaxdesmarais** [comment]
Hello @gokulnair2001 -

Happy to hear you were able to resolve the issue. Our SDK does not track the total checkout time or time when a transaction was completed. That said you could use [`Date`](https://developer.apple.com/documentation/foundation/date/), [`CFAbsoluteTimeGetCurrent`](https://developer.apple.com/documentation/corefoundation/1543542-cfabsolutetimegetcurrent), [`DispatchTime`](https://developer.apple.com/documentation/dispatch/dispatchtime) or a third party library depending on your needs. From there you can implement the desired time tracking tool to start within `Checkout.start` and end in the `onApprove` callback if you are looking for the total transaction time. If you are just looking for the time when payment is completed, you can just log this with the desired implementation above in the `onApprove` callback.

I hope the above points you in the right direction as this is outside of the scope of our SDK so our support on implementation is limited. If you have other questions related to the PayPal SDK, please let me know, otherwise I can close out this issue.

**Comment by gokulnair2001** [comment]
Thanks a lot @jaxdesmarais , happy to see developers at PayPal are constantly helping the users. It was a great having convo with you. Thanks for the timer solution, will implement it by myself :)
