### ISSUE TITLE
[🐞] Fatal Exception: NSInternalInconsistencyException

### ISSUE THREAD

**Issue by ryantallmadge** [paypal/paypalcheckout-ios#74]
### 🐞 Describe the Bug

PayPalCheckout
__hidden#50392_ - Line 156
_hidden#50312_ + 156

Fatal Exception: NSInternalInconsistencyException
Invalid update: invalid number of rows in section 0. The number of rows contained in an existing section after the update (0) must be equal to the number of rows contained in that section before the update (9), plus or minus the number of rows inserted or deleted from that section (0 inserted, 0 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).

### 🔬 Minimal Reproduction
Currently can not reproduce, however we are seeing this crash in out analytics. 

### 😕 Actual Behavior
Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x129708 __exceptionPreprocess
1  libobjc.A.dylib                0x287a8 objc_exception_throw
2  CoreFoundation                 0x2b3b8 -[CFPrefsSearchListSource addManagedSourceForIdentifier:user:]
3  Foundation                     0x7e4c4 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:]
4  UIKitCore                      0xdc24d4 -[UITableView _Bug_Detected_In_Client_Of_UITableView_Invalid_Number_Of_Rows_In_Section:]
5  UIKitCore                      0xdc1de4 -[UITableView _endCellAnimationsWithContext:]
6  UIKitCore                      0xdd9d80 -[UITableView endUpdatesWithContext:]
7  UIKitCore                      0xdd9f70 -[UITableView _performBatchUpdates:withContext:completion:]
8  UIKitCore                      0xdda0b0 -[UITableView performBatchUpdates:completion:]
9  PayPalCheckout                 0x3a7598 _hidden#50312_ + 156 (__hidden#50392_:156)
10 PayPalCheckout                 0x1c9ce4 _hidden#33_ (__hidden#1299_)
11 UIKitCore                      0xa5e40 -[UIViewPropertyAnimator _runAnimations]
12 UIKitCore                      0xad570 __49-[UIViewPropertyAnimator startAnimationAsPaused:]_block_invoke_2
13 UIKitCore                      0xad39c __49-[UIViewPropertyAnimator startAnimationAsPaused:]_block_invoke
14 UIKitCore                      0xad4dc __49-[UIViewPropertyAnimator startAnimationAsPaused:]_block_invoke.1126
15 UIKitCore                      0xacb44 -[UIViewPropertyAnimator _setupAnimationTracking:]
16 UIKitCore                      0xad0e4 -[UIViewPropertyAnimator startAnimationAsPaused:]
17 PayPalCheckout                 0xcde78 _hidden#7122_ + 1092 (__hidden#7577_:1092)
18 PayPalCheckout                 0xcd3e0 _hidden#7118_ (__hidden#1299_)
19 UIKitCore                      0xa6704 -[UIViewPropertyAnimator _executeCompletionHandlerWithFinalPosition:]
20 UIKitCore                      0xa6804 -[UIViewPropertyAnimator _runCompletions:finished:]
21 UIKitCore                      0xa53bc __61-[UIViewPropertyAnimator _setupAssociatedViewAnimationState:]_block_invoke
22 UIKitCore                      0x10ffd58 -[UIViewAnimationBlockDelegate _didEndBlockAnimation:finished:context:]
23 UIKitCore                      0x10d23d0 -[UIViewAnimationState sendDelegateAnimationDidStop:finished:]
24 UIKitCore                      0x10d2934 -[UIViewAnimationState animationDidStop:finished:]
25 QuartzCore                     0x17d8ec CA::Layer::run_animation_callbacks(void*)
26 libdispatch.dylib              0x481c _dispatch_client_callout
27 libdispatch.dylib              0x12c70 _dispatch_main_queue_callback_4CF
28 CoreFoundation                 0xa3340 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
29 CoreFoundation                 0x9d218 __CFRunLoopRun
30 CoreFoundation                 0x9c308 CFRunLoopRunSpecific
31 GraphicsServices               0x3734 GSEventRunModal
32 UIKitCore                      0xbca75c -[UIApplication _run]
33 UIKitCore                      0xbcffcc UIApplicationMain
34 Underdog                       0x4b6c main + 18 (main.swift:18)
35 libdyld.dylib                  0x1cf8 start

### 🤔 Expected Behavior
No crashes

### 🌍 Environment

- iOS version: - 14.X.X - 15.X.X
- SDK version (`Checkout.version`): - 0.66.0

**Comment by aj-bartocci** [comment]
Do we have any update on this?

**Comment by jonathajones** [comment]
Hi @aj-bartocci  / @ryantallmadge  - 

This should be resolved in the latest release,`0.81.0` - https://github.com/paypal/paypalcheckout-ios/releases/tag/0.81.0
Please update and let us know if you're still seeing this. Closing this for now. If you continue to see this, please open up a new issue. 

Thanks!
