### ISSUE TITLE
How to hide Shipping Addresss in Paypal Checkout

### ISSUE THREAD

**Issue by sranipa** [paypal/paypalcheckout-ios#75]
Hello, 

I have integrate paypalcheckout-iOS sdk for payment. My feature is for sending money to friend. It is not related to any shipping feature. My code for payment is like below

    func makePaypalPayment(amount:String,userEmail:String,eChitthiAmount:String) {
                  Checkout.start(
                    createOrder: { createOrderAction in 
                let amountForeChitthi = PurchaseUnit.Amount(currencyCode: .usd, value: eChitthiAmount)
                let purchaseUnitForeChitthi = PurchaseUnit(amount: amountForeChitthi,referenceId:UUID().uuidString)
                 
                let amount = PurchaseUnit.Amount(currencyCode: .usd, value: amount)
                let payeeDetail = PurchaseUnit.Payee(emailAddress:userEmail)
                let purchaseUnit = PurchaseUnit(amount: amount,referenceId:UUID().uuidString, payee: payeeDetail)
                let order : OrderRequest = OrderRequest(intent: .capture, purchaseUnits: [purchaseUnit,purchaseUnitForeChitthi])
                 
                createOrderAction.create(order: order)
                
            }, onApprove: { approval in
                approval.actions.capture { (response, error) in
                    print("payment success")
                }
            }, onCancel: {
                 print("payment cancelled by client")
            }, onError: { error in
                print("payment have some error")
            }
        )
    }

When paypal default screen will open it have a default shipping address information. I don't want to display shipping address detail to user. Can you please help me in that.

![Simulator Screen Shot - iPhone 11 - 2021-10-29 at 16 59 06](https://user-images.githubusercontent.com/17876312/139501120-696f51b0-c872-42e4-865a-0be7d8687992.png)

Any help will be appreciate. Thanks.

**Comment by jaxdesmarais** [comment]
Hello @sranipa -

You can hide the shipping view by passing the following when creating the order:
```
let applicationContext = OrderApplicationContext(shippingPreference: .noShipping)
let order = OrderRequest(intent: .capture, purchaseUnits: [purchaseUnit, purchaseUnitForeChitthi], applicationContext: applicationContext)
```

**Comment by sranipa** [comment]
Hi @jaxdesmarais 

Thanks a lot. I added this and it's working. Thanks again for your help. 

I have one more question. Right now I am making one chat application in that we have one feature in that on special occasion(like Birthday, Anniversary etc) user can send money to his/her friend. So for sending money we are using paypal.

**Comment by sranipa** [comment]
Hi @jaxdesmarais

Thanks a lot. I added this and it's working. Thanks again for your help.

I have one more question. Right now I am making one chat application in that we have one feature, in that on special occasion(like Birthday, Anniversary etc) user can send money to his/her friend. So for sending money we are using paypal.

And our payment flow is like. when user send gift amount to friend that time 0.1% goes to our application's account. So for that I have added code into my app like above which I wrote. In that we are making two transaction one for user and one for our application fee. Is it right way for this scenario ?

Because right now we are making two transaction so it is taking two time paypal fee. I try to use **PlatformFees** using **paymentInstruction** but it is ignoring my platform fee. For use this PlatformFees we require any other specific setup ? or any other way is better for my app requirement scenario ?

My developer account type is : Personal account.

**Comment by jaxdesmarais** [comment]
Hello @sranipa -

The `PlatformFees` object is only applicable to merchants that been enabled for PayPal Commerce Platform for Marketplaces and Platforms capability. I would recommend reaching out to [PayPal support directly](https://www.paypal-support.com/s/?language=en_US) for additional details on if you are eligible for this type of account set up as we do not have any insight into the approval process for these accounts.

**Comment by sranipa** [comment]
HI @jaxdesmarais, 

Thanks for this information. It is very helpful for me. Thanks again.
