### ISSUE TITLE
[🐞] Bug Report Unable to login for the first time

### ISSUE THREAD

**Issue by ositov** [paypal/paypalcheckout-ios#82]
Hi,
The mobile iOS app we are developing and maintaining does use PayPal SDK. We’ve been forced to migrate to the newer version of the SDK when Apple deprecated  the WebView control and, in turn, deprecation of the previous PayPal SDK. However, unfortunately, we can’t manage it to correctly work so far. We already contacted with the PayPal support, but they wasn’t able to help as well. So we decided to ask for a help here; maybe either developers or someone else with the same/similar problem might help us somehow. Search through the issues list revealed that one of our problem is already reported here and is in the research stage (double login windows). Here is another one: no purchase happens on the 1st run of app. Here is the details:
The following code does programmatically start the SDK.
<img width="824" alt="Screenshot 2021-11-25 at 13 21 18" src="https://user-images.githubusercontent.com/28897139/143432567-13becf34-f110-455e-8aa2-71be03edabcb.png">
On the 1st app start, the following events occurs on the attempt to do a purchase via PayPal:
The login window appears. Entering login and pass, clicking to the “Log in” button. The window disappears and nothing happens after that. This thing can be observed at 0:40 of the attached video. It’s also should be noticeable in the video, that some breakpoints are set in the code. App didn’t stop on any of them (so nothing have been received from PayPal side). Then press “Pay” button again. This time there is the following error:
`1 --> Error: Error Domain=org.openid.appauth.general Code=-3 "(null)" UserInfo={NSUnderlyingError=0x600001adc870 {Error Domain=com.apple.AuthenticationServices.WebAuthenticationSession Code=3 "The UIWindowScene for the returned window was not in the foreground active state." UserInfo={NSDebugDescription=The UIWindowScene for the returned window was not in the foreground active state.}}}

2 --> Reason: The operation couldn’t be completed. (org.openid.appauth.general error -3.)`

I placed two marks, 1 and 2, into the code snippet to illustrate where the error is caught; the corresponding moment in video at 0:57.After that, the purchase won’t be completed, no matter how many attempts we will do. If the app will be stopped and then started again - the purchase happens without any errors

https://user-images.githubusercontent.com/28897139/143433408-667434d0-59b9-4468-a9d9-8114e40b01ae.mp4

.

**Comment by minhthenguyen** [comment]
Hi @ositov 
To create an order with PayPal SDK, you can either use `[action createWithOrder: completion:]` or `[action setWithOrderId]`, but not both.
- You can use `createWithOrder` if you want the SDK to create an order for you.
- Or if you already have an orderID (ie. by creating an order using one of PayPal's APIs in your backend), you can pass the orderID to the SDK with `setWithOrderId`.

In this case, I believe you want the SDK to create an order for you, so you can implement the `createOrder` callback like so:
```
[PPCheckout startWithPresentingViewController: self createOrder:^(PPCCreateOrderAction *action) {
    PPCOrderRequest *order = [self createNewOrder];
    [action createWithOrder:order completion:^(NSString *orderId) {
        // You can save the orderID here for your bookkeeping purpose, or leave this closure blank
    }];
} ... ];
```

Can you try that and let me know if it fixes the problem?

**Comment by minhthenguyen** [comment]
Closing ticket due to inactivity. Feel free to reopen if you still experience the issue. Thank you!
