### ISSUE TITLE
No such module '_Concurrency'

### ISSUE THREAD

**Issue by goyanimaulik** [paypal/paypalcheckout-ios#83]
I am using 12.5.1 XCode and getting error like this

No such module '_Concurrency'

Please help

**Comment by jonathajones** [comment]
Hi @goyanimaulik - 
Assuming you're on version `0.79.0` - for now, you can resolve the issue by downgrading to `0.77.0`. This will also be fixed in the next release.

**Comment by jonathajones** [comment]
This should be resolved in version `0.81.0`: https://github.com/paypal/paypalcheckout-ios/releases/tag/0.81.0
