### ISSUE TITLE
[🐞] Login requested twice in checkout process

### ISSUE THREAD

**Issue by ilendemli** [paypal/paypalcheckout-ios#86]
### 🐞 Describe the Bug
Whether I use the sample app or the app I am currently working on, the PayPal checkout process requires me to login twice. Similar or same to Issue #48 

### 🔬 Minimal Reproduction
Downloaded the Sample project. Set clientId as well as returnUrl. Start the checkout process.

### 😕 Actual Behavior
Checkout requires me to login twice in separate windows, losing the login credentials in the second window that I have put in in the first window.

### 🤔 Expected Behavior
Login and checkout in the same window.

### 🌍 Environment

- iOS version: 13.7, 14.5, 15
- SDK version (`Checkout.version`): 0.26.0 as well as 0.81.0

### ➕ Additional Context

https://user-images.githubusercontent.com/2271750/148936817-cf56a912-8d94-4acc-8c7f-7d73c9edf1c9.mp4

**Comment by jan-bednar** [comment]
I can confirm this behaviour, we have the same issue on version 0.79 and 0.81

**Comment by jonathajones** [comment]
Hi @jan-bednar  - Thanks for opening the issue. If you could reproduce, could you provide us with the contents of `State.correlationIDs`? I'm guessing there is an eligibility issue, which is causing you to fall back to the web experience. We are investigating why the authentication tokens are not properly authenticating some users in the fallback scenario.

**Comment by jan-bednar** [comment]
@jonathajones this is the dump after confirming payment, after I had to log in twice:

```
(lldb) po PayPalCheckout.State.correlationIDs.fundingEligibilityDebugID
nil

(lldb) po PayPalCheckout.State.correlationIDs.eligibilityDebugID
▿ Optional<String>
  - some : "4fdfe148ad77b"

(lldb) po PayPalCheckout.State.correlationIDs.updateClientConfigDebugID
▿ Optional<String>
  - some : "b08554b79afa2"

(lldb) po PayPalCheckout.State.correlationIDs.lsatUpgradeDebugID
nil

(lldb) po PayPalCheckout.State.correlationIDs.fetchPayloadDebugID
nil

(lldb) po PayPalCheckout.State.correlationIDs.fetchCartDebugIDs
0 elements

0 elements

(lldb) po PayPalCheckout.State.correlationIDs.currencyConversionDebugID
nil

(lldb) po PayPalCheckout.State.correlationIDs.completeSCADebugID
nil

(lldb) po PayPalCheckout.State.correlationIDs.finishCheckoutDebugID
nil

(lldb) po PayPalCheckout.State.correlationIDs.riskCorrelationID
nil

(lldb) po PayPalCheckout.State.correlationIDs.sessionIDs
<PPCSessionIDs: 0x2814cebe0>

(lldb) po PayPalCheckout.State.correlationIDs.sessionIDs.sdkSessionID
▿ Optional<String>
  - some : "80B81F9C-7DE0-44CC-821D-5CDDAAF05DE7"

(lldb) po PayPalCheckout.State.correlationIDs.sessionIDs.orderSessionID
▿ Optional<String>
  - some : "941B5391-28F8-40BE-A5A1-7591613A41A8"
```

**Comment by ilendemli** [comment]
Hey! Sorry for the late response.
Here are mine, after setting Config but before starting the checkout process:

<details>
<summary>prints</summary>

```
(lldb) po PayPalCheckout.State.correlationIDs.fundingEligibilityDebugID
▿ Optional<String>
  - some : "6c854cb52c5ad"

(lldb) po PayPalCheckout.State.correlationIDs.eligibilityDebugID
nil

(lldb) po PayPalCheckout.State.correlationIDs.updateClientConfigDebugID
nil

(lldb) po PayPalCheckout.State.correlationIDs.lsatUpgradeDebugID
nil

(lldb) po PayPalCheckout.State.correlationIDs.fetchPayloadDebugID
nil

(lldb) po PayPalCheckout.State.correlationIDs.fetchCartDebugIDs
0 elements

(lldb) po PayPalCheckout.State.correlationIDs.currencyConversionDebugID
nil

(lldb) po PayPalCheckout.State.correlationIDs.completeSCADebugID
nil

(lldb) po PayPalCheckout.State.correlationIDs.finishCheckoutDebugID
nil

(lldb) po PayPalCheckout.State.correlationIDs.riskCorrelationID
nil

(lldb) po PayPalCheckout.State.correlationIDs.sessionIDs.sdkSessionID
nil

(lldb) po PayPalCheckout.State.correlationIDs.sessionIDs.orderSessionID
nil

```
</details>

inside the createOrder callback:

<details>
<summary>prints</summary>

```
(lldb) po PayPalCheckout.State.correlationIDs.fundingEligibilityDebugID
nil

(lldb) po PayPalCheckout.State.correlationIDs.eligibilityDebugID
nil

(lldb) po PayPalCheckout.State.correlationIDs.updateClientConfigDebugID
nil

(lldb) po PayPalCheckout.State.correlationIDs.lsatUpgradeDebugID
nil

(lldb) po PayPalCheckout.State.correlationIDs.fetchPayloadDebugID
nil

(lldb) po PayPalCheckout.State.correlationIDs.fetchCartDebugIDs
0 elements

(lldb) po PayPalCheckout.State.correlationIDs.currencyConversionDebugID
nil

(lldb) po PayPalCheckout.State.correlationIDs.completeSCADebugID
nil

(lldb) po PayPalCheckout.State.correlationIDs.finishCheckoutDebugID
nil

(lldb) po PayPalCheckout.State.correlationIDs.riskCorrelationID
nil

(lldb) po PayPalCheckout.State.correlationIDs.sessionIDs.sdkSessionID
▿ Optional<String>
  - some : "C69E359D-50FA-4728-8682-EA0FE57AE2AC"

(lldb) po PayPalCheckout.State.correlationIDs.sessionIDs.orderSessionID
▿ Optional<String>
  - some : "6049C52B-7869-43A3-9F9D-CE1B13D46D06"
```
</details>

**Comment by stephenhyde** [comment]
Right now my phone always triggers a web fallback. I have never seen the checkout UI Overlay.

IPhone 12
Software Version 15.4.1

Our app is currently using .84 but .88 does not seem to change anything.

Is there anything I can provide you during the checkout to figure out what going on?

**Comment by jonathajones** [comment]
Hi @stephenhyde  - 
There are many things that could currently cause the SDK to trigger a web fallback, rather than present the native UI experience. For example - device location, user account location, possessing crypto, and unsupported transaction types would all cause the SDK to fall back to web.

1. What region are you in? 
2. Is this in sandbox, or prod?
3. What API are you using to generate the tokens you are passing to the SDK? 

We're currently working to expand supported native flows, so the hope is that we would reduce the number of web fallbacks that users see. 

We are still working with our authentication team to resolve the double login scenario the issue was originally opened with.

**Comment by stephenhyde** [comment]
@jonathajones sorry for the delay. I did not see your response.

Want to confirm that we updated to 0.94.0 and I consistently get fallback.

1. Canada (Ontario)
2. Sandbox
3. I am just passing the Paypal client id to the client from the backend. I use an orders API to give the client an order id.

 My iPhone 12 has 100% reproducibility for this fallback, if there is anything I can do to help you guys nail it down, lmk! I am a backend developer but I can get the iOS developer on the team to help pull anything off the phone if needed.

**Comment by ilendemli** [comment]
@jonathajones Hey! Any updates regarding this?

**Comment by jonathajones** [comment]
Hi @ilendemli / @stephenhyde  - Apologies on the incredible delay here - the email notifications from this thread went to my spam here. 

The current version is `0.109.0` - but i'm not sure if the behavior you're seeing has been resolved. 
If you could reproduce this behavior in Sandbox and post an EC token of the flow, I'll be able to triage that with the identity team that is responsible for this flow.

I'll keep an eye on this thread so that I don't miss any more updates. Again, apologies for the delay.

**Comment by stephenhyde** [comment]
@jonathajones We have updated our SDK to your most recent version. I am pretty certain it's resolved. I was able to reproduce 100% of the web fallback flow in previous versions and now everything is native. From login -> checkout all native. Looks great.

Thanks for looking into this.

**Comment by jonathajones** [comment]
Thanks @stephenhyde ! The native flow you're seeing is the OTP flow - i'm glad it's working well for you. To verify the behavior has been fixed on the web side of things (the issue was reported for the web login flow) - would you be able to select the option to login with your username / password when presented with the OTP entry fields?
