### ISSUE TITLE
[🐞] Bug Report

### ISSUE THREAD

**Issue by sranipa** [paypal/paypalcheckout-ios#87]
Hi I have added PayPalCheckout into my swift application. And When I try to capture order and that time paypal will ask for signin and it will open webpage for paypal singIn but every time it getting error
![Simulator Screen Shot - iPhone 12 Pro - 2022-01-11 at 13 44 50](https://user-images.githubusercontent.com/17876312/149003510-091c6871-d14d-4702-991a-4572061e4f12.png)
 
Can you please help me why always gettting invalid scope. I am testing in sandbox mode.

**Comment by AAlboghdady** [comment]
May I know how did you fix it?
@sranipa

**Comment by sranipa** [comment]
@AAlboghdady, It was issue in my code. I have added multiple value into **PurchaseUnit** because of that I was facing issue . You are facing same issue ? Then please share your code with me so I can check it and compare with my code and try to find issue. Thanks.

**Comment by sranipa** [comment]
@AAlboghdady

**Comment by AAlboghdady** [comment]
> @AAlboghdady
> 
> self.package?.price is alway return string value ? If not then you need to convert into string then it will work.
> 
> I have added code like this let amount = PurchaseUnit.Amount(currencyCode: .usd, value: String(format: "%.2f", transactionAmountOfUser))

My price was decimal, and this was a problem and the lower case.
Thanks again.

**Comment by rohitramkumar** [comment]
@jonathajones I'm still experiencing this issue even though I have enabled the "Name" and "Email" scopes in the sandbox environment.

I am doing a server-side integration and my backend is able to successfully create an order ID but after that I see this error in the native flow.
