### ISSUE TITLE
PayPal Checkout Setup Error

### ISSUE THREAD

**Issue by gokulnair2001** [paypal/paypalcheckout-ios#88]
### Describe Your Issue
Not able to set up PayPal checkout 

it's giving me an error of ***<PPCCorrelationIDs: 0x600003c95340>***

the code snippet is the same which I have used in #67 

Please do have a look and let me know what I can do since the snippet was working absolutely fine for a month and now suddenly it's giving me this error i.e. <PPCCorrelationIDs: 0x600003c95340>

**Comment by minhthenguyen** [comment]
Hi @gokulnair2001
Can you please add `config.debugEnabled = true` like so:
```
func configurePaypal() {
        let config = ...
        config.debugEnabled = true
        Checkout.set(config: config)
}
```
then reproduce the bug? That will copy the debug information into your clipboard. If you can paste it here, that'll help us a lot with debugging this issue.

Also, a video screenshot of the bug would be great too.
Thank you

**Comment by jonathajones** [comment]
Stale and need more information. Please open a new issue with code snippet / reproduction steps if it persists.
