### ISSUE TITLE
Payment initiation using Direct API integration pattern and non-native experience mode fails before even launching Hermes experience in SafariViewController

### ISSUE THREAD

**Issue by SaurabhNi** [paypal/paypalcheckout-ios#9]
If I try to integrate with native xo sdk using the Direct API integration pattern and browser only mode as YES (non-native experience), the payment initiation itself fails as SDK is not able to form the Hermes checkout URL using the EC token and fails at that step and hence the Hermes experience itself doesn't gets launched in SafariViewController. Below is the code to launch and error stack trace : -

For brevity I haven't put the logic to fetch the payToken variable in below extract from the merchant server side code using Server side PayPal Payments API calls, but that logic works fine and payToken is passed successfully in below code.

                **PYPLCheckout* checkout=[PYPLCheckout sharedInstance];
                checkout.serviceEnvironment = kPYPLEnvironment_SandBox;
                checkout.webBrowserOnlyMode=@YES;
                [checkout startCheckoutWithECToken:payToken withDelegate: self];**

2018-08-01 16:20:42.367133+0530 PayPalNativeCheckout[7445:426171] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** +[NSURLComponents initWithURL:resolvingAgainstBaseURL:]: nil URLString parameter'
*** First throw call stack:
(
                        0   CoreFoundation                      0x000000010e32f1e6 __exceptionPreprocess + 294
                        1   libobjc.A.dylib                     0x000000010d25e031 objc_exception_throw + 48
                        2   CoreFoundation                      0x000000010e3a4975 +[NSException raise:format:] + 197
                        3   Foundation                          0x000000010ccb5f22 -[__NSConcreteURLComponents initWithURL:resolvingAgainstBaseURL:] + 120
                        4   Foundation                          0x000000010ccb5e91 +[NSURLComponents componentsWithURL:resolvingAgainstBaseURL:] + 53
                        5   PayPalNativeCheckout                0x000000010c891bf1 -[PYPLCheckout getHermesUrl] + 147
                        6   PayPalNativeCheckout                0x000000010c89186f -[PYPLCheckout startAuthentication] + 397
                        7   PayPalNativeCheckout                0x000000010c89197e -[PYPLCheckout startCheckoutWithECToken:withDelegate:] + 165
                        8   PayPalNativeCheckout                0x000000010c885085 __30-[ViewController startECFlow:]_block_invoke + 693
                        9   CFNetwork                           0x000000010daf0e76 __75-[__NSURLSessionLocal taskForClass:request:uploadFile:bodyData:completion:]_block_invoke + 19
                        10  CFNetwork                           0x000000010daf06c7 __49-[__NSCFLocalSessionTask _task_onqueue_didFinish]_block_invoke + 147
                        11  Foundation                          0x000000010cc74363 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
                        12  Foundation                          0x000000010cc741ca -[NSBlockOperation main] + 68
                        13  Foundation                          0x000000010cc726b2 -[__NSOperationInternal _start:] + 766
                        14  libdispatch.dylib                   0x0000000112e767ec _dispatch_client_callout + 8
                        15  libdispatch.dylib                   0x0000000112e7bdb8 _dispatch_block_invoke_direct + 592
                        16  libdispatch.dylib                   0x0000000112e767ec _dispatch_client_callout + 8
                        17  libdispatch.dylib                   0x0000000112e7bdb8 _dispatch_block_invoke_direct + 592
                        18  libdispatch.dylib                   0x0000000112e7bb48 dispatch_block_perform + 109
                        19  Foundation                          0x000000010cc6e75b __NSOQSchedule_f + 337
                        20  libdispatch.dylib                   0x0000000112e767ec _dispatch_client_callout + 8
                        21  libdispatch.dylib                   0x0000000112e7cad9 _dispatch_continuation_pop + 967
                        22  libdispatch.dylib                   0x0000000112e7af54 _dispatch_async_redirect_invoke + 780
                        23  libdispatch.dylib                   0x0000000112e8236c _dispatch_root_queue_drain + 664
                        24  libdispatch.dylib                   0x0000000112e82076 _dispatch_worker_thread3 + 132
                        25  libsystem_pthread.dylib             0x00000001133a1169 _pthread_wqthread + 1387
                        26  libsystem_pthread.dylib             0x00000001133a0be9 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by dmikey** [comment]
Hi this should be fixed by now, can you retest?
