### ISSUE TITLE
[🐞] Crash on ShippingChangeAction.patch(request: , onComplete: )

### ISSUE THREAD

**Issue by rokaspoq** [paypal/paypalcheckout-ios#91]
### 🐞 Describe the Bug
If you try to add shipping options app crashes. 

### 🔬 Minimal Reproduction
Try this callback
```
        Checkout.setOnShippingChangeCallback { shipping, shippingAction in
            let reguest = PatchRequest()
            reguest.add(shippingOptions: [
                .init(id: "id", label: "label", selected: true, type: .shipping)
            ], referenceId: nil)
            
            shippingAction.patch(request: reguest) { success, error in
                
            }
        }
```

### 😕 Actual Behavior
This is the error message: `Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of rows in section 0. The number of rows contained in an existing section after the update (9) must be equal to the number of rows contained in that section before the update (0), plus or minus the number of rows inserted or deleted from that section (0 inserted, 0 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out). Table view: <PayPalCheckout.PaysheetContainerView: 0x7fb39a8b7e00; baseClass = UITableView; frame = (0 892; 428 0); clipsToBounds = YES; alpha = 0; gestureRecognizers = <NSArray: 0x600001ea1aa0>; animations = { opacity=<CABasicAnimation: 0x6000010d1920>; }; layer = <CALayer: 0x6000010e9020>; contentOffset: {0, 0}; contentSize: {428, 0}; adjustedContentInset: {0, 0, 0, 0}; dataSource: <PayPalCheckout.ContainerVM: 0x6000010e9920>>'`

### 🤔 Expected Behavior
App should display shipping methods.

### 🌍 Environment

- iOS version: - 15.2
- SDK version (`Checkout.version`): - 0.81

**Comment by minhthenguyen** [comment]
Hi @rokaspoq 
Thank you for reporting the issue.
This has been fixed internally and will be available in the next version.
We'll keep you posted in here once it's released.

**Comment by rokaspoq** [comment]
hey @minhthenguyen I raised another [isuue](https://github.com/paypal/paypalcheckout-ios/issues/93) related to shipping methods. It is reproducible for 0.84.0 version. If you tap a shipping method while methods are loading you might get the same crash. It happens randomly and might take some time to replicate it.

**Comment by minhthenguyen** [comment]
Thanks @rokaspoq, I saw your other issue and am investigating it.
Can you please help us verify that the crash in this issue has gone with version 0.84.0?

**Comment by rokaspoq** [comment]
@minhthenguyen yes, it's version 0.84.0

**Comment by minhthenguyen** [comment]
Thank you, I'll close this issue and keep you posted on the crash in the other issue :smile:
