### ISSUE TITLE
[🐞] Crash when tapping a shipping method while methods are loading

### ISSUE THREAD

**Issue by rokaspoq** [paypal/paypalcheckout-ios#93]
### 🐞 Describe the Bug
If you tap a shipping method while methods are loading you might get a crash.

### 🔬 Minimal Reproduction
Try to tap a shipping method for multiple times while methods are loading. It happens randomly and might take some time to reproduce it.

### 😕 Actual Behavior
There is this crash
`*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of rows in section 0. The number of rows contained in an existing section after the update (1) must be equal to the number of rows contained in that section before the update (9), plus or minus the number of rows inserted or deleted from that section (0 inserted, 0 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out). Table view: <PayPalCheckout.PaysheetContainerView: 0x7fc979115000; baseClass = UITableView; frame = (0 324.667; 428 443); clipsToBounds = YES; alpha = 0; gestureRecognizers = <NSArray: 0x600003672370>; animations = { opacity=<CABasicAnimation: 0x600003e1b3a0>; UIPacingAnimationForAnimatorsKey=<CABasicAnimation: 0x600003e1ede0>; }; layer = <CALayer: 0x600003eace20>; contentOffset: {0, 0}; contentSize: {428, 442.90038681030273}; adjustedContentInset: {0, 0, 0, 0}; dataSource: <PayPalCheckout.ContainerVM: 0x600003e5ac40>>'`

### 🤔 Expected Behavior
App should open a shipping method selection view.

### 🌍 Environment

- iOS version: - 15.2
- SDK version (`Checkout.version`): -0.84.0

### ➕ Additional Context
https://user-images.githubusercontent.com/40168471/152148769-fa4c02c3-a117-4fb7-8706-e7e911635475.mov

**Comment by minhthenguyen** [comment]
@rokaspoq 
Thank you for reporting this issue. We're investigating this and will keep you posted when the fix for this is available.
