### ISSUE TITLE
[🐞] Crash - PayPalCheckout.PaysheetContainerView number of rows before not equal to number of rows after

### ISSUE THREAD

**Issue by quintonpryce** [paypal/paypalcheckout-ios#95]
### 🐞 Describe the Bug

This is our top crash in our app right now followed closely by another crash from this PayPal framework.

Invalid update: invalid number of rows in section 0. The number of rows contained in an existing section after the update (1) must be equal to the number of rows contained in that section before the update (9), plus or minus the number of rows inserted or deleted from that section (0 inserted, 0 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out). Table view: <PayPalCheckout.PaysheetContainerView: 0x10aec6400; baseClass = UITableView; frame = (0 394; 375 152); clipsToBounds = YES; alpha = 0; gestureRecognizers = <NSArray: 0x280d09710>; animations = { opacity=<CABasicAnimation: 0x280339360>; UIPacingAnimationForAnimatorsKey=<CABasicAnimation: 0x280339960>; }; layer = <CALayer: 0x28034c800>; contentOffset: {0, 0}; contentSize: {375, 152}; adjustedContentInset: {0, 0, 0, 0}; dataSource: <PayPalCheckout.ContainerVM: 0x28034cf40>>

### 🌍 Environment

- iOS version: - iOS 14 & 15 (We only have these two targeted)
- SDK version (`Checkout.version`): - 0.81.0

**Comment by quintonpryce** [comment]
Let me know how I can be useful here, this is our highest rating crash.

**Comment by quintonpryce** [comment]
I just saw that 0.84.0 contains a fix for a tableView crash. I'm going to update to the version for my release this week & see if it mitigates my crashes

**Comment by minhthenguyen** [comment]
Hi @quintonpryce 
Thank you for reporting the two crash issues. We're looking into the other one. I'll close this one as it has been fixed in 0.84.0, but please feel free to open another if you find the issue persists with our latest version.
