### ISSUE TITLE
[🐞] Login requested twice in checkout process

### ISSUE THREAD

**Issue by devaselvi23** [paypal/paypalcheckout-ios#97]
### 🐞 Describe the Bug
Whether I use the sample app or the app I am currently working on, the PayPal checkout process requires me to login twice. Similar or same to Issue https://github.com/paypal/paypalcheckout-ios/issues/86

### 🔬 Minimal Reproduction
Create a Sample project. Set clientId as well as returnUrl. Start the checkout process.

### 😕 Actual Behavior
Checkout requires me to login twice in separate windows, losing the login credentials in the second window that I have put in in the first window.
Note: I didn't use paypal checkout button

### 🤔 Expected Behavior
The login window should appear only one time.

### 🌍 Environment

- iOS version: - 14.5, 15.1
- SDK version (`Checkout.version`): - 0.84

https://user-images.githubusercontent.com/100335832/155493520-f098c929-70fc-4866-8876-7fdfa4fccfc6.mp4

.0

### ➕ Additional Context
Add any other context about the problem here. Screenshots or videos that show the issue are very helpful.

**Comment by jonathajones** [comment]
Hi @devaselvi23 - Sorry for the delayed response. Could you share what region your paypal account is in? Different regions have different authentication requirements, so users outside the USA will often see a second auth required after login. We are working with our authentication team to better handle authentication in other regions.

**Comment by devaselvi23** [comment]
Hello Sir,
Thanks for your reply.
And sorry for the delayed response.
Our paypal account region is Singapore.
We only use Singapore now.
Please help us to clear this issue.
Thank you

**Comment by jonathajones** [comment]
Just updating to let you know that we're still working on this with our authentication team. Thanks for the patience.

**Comment by jonathajones** [comment]
This should be resolved except in some SCA compliance cases
