### ISSUE TITLE
[🐞] Bug Report

### ISSUE THREAD

**Issue by ryantallmadge** [paypal/paypalcheckout-ios#98]
### 🐞 Describe the Bug
Fatal Exception: NSInternalInconsistencyException

### 🔬 Minimal Reproduction
Not sure how to reproduce, bug is coming in our Crashlytics

### 😕 Actual Behavior
Fatal Exception: NSInternalInconsistencyException
Invalid update: invalid number of rows in section 0. The number of rows contained in an existing section after the update (0) must be equal to the number of rows contained in that section before the update (9), plus or minus the number of rows inserted or deleted from that section (0 inserted, 0 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out). Table view: <PayPalCheckout.PaysheetContainerView: 0x12ca67600; baseClass = UITableView; frame = (0 489.667; 390 199.333); clipsToBounds = YES; alpha = 0; gestureRecognizers = <NSArray: 0x2819cd860>; animations = { opacity=<CABasicAnimation: 0x2816e0ea0>; UIPacingAnimationForAnimatorsKey=<CABasicAnimation: 0x2816e0e80>; }; layer = <CALayer: 0x28176dc60>; contentOffset: {0, 0}; contentSize: {390, 199.33333206176758}; adjustedContentInset: {0, 0, 0, 0}; dataSource: <PayPalCheckout.ContainerVM: 0x281740e20>>

### 🤔 Expected Behavior
No errors

### 🌍 Environment

- iOS version: - 14+
- SDK version (`Checkout.version`): - 0.77.0

### ➕ Additional Context
0
CoreFoundation
__exceptionPreprocess
8
UIKitCore
-[UITableView performBatchUpdates:completion:]
9
PayPalCheckout
__hidden#50798_ - Line 156
_hidden#50718_ + 156
10
PayPalCheckout
__hidden#1300_
_hidden#33_
11
UIKitCore
-[UIViewPropertyAnimator _runAnimations]
16
UIKitCore
-[UIViewPropertyAnimator startAnimationAsPaused:]
17
PayPalCheckout
__hidden#7717_ - Line 1098
_hidden#7263_ + 1098
18
PayPalCheckout
__hidden#1300_
_hidden#7259_
19
UIKitCore
-[UIViewPropertyAnimator _executeCompletionHandlerWithFinalPosition:]
30
UIKitCore
UIApplicationMain

**Comment by jonathajones** [comment]
Hi @ryantallmadge - 
We've caught this issue recently; if you upgrade to version `0.84.0`, you should see it resolved : https://github.com/paypal/paypalcheckout-ios/releases/tag/0.84.0

**Comment by ryantallmadge** [comment]
Thank you, will update!
