### ISSUE TITLE
[🐞] Crash Report on __hidden#32877_ - Line 156

### ISSUE THREAD

**Issue by alihanaktay** [paypal/paypalcheckout-ios#99]
### 🐞 Describe the Bug
We have just updated library to 0.88, started to get a several crashes on the __hidden#32877_ - Line 156.

### 🔬 Minimal Reproduction
Can't reproduce on our side.

### 😕 Actual Behavior
Crashed: com.apple.NSURLSession-delegate
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000ea17ba4666f0

Crashed: com.apple.NSURLSession-delegate
0  libswiftCore.dylib             0x388c9c _swift_release_dealloc + 32
1  PayPalCheckout                 0x223004 _hidden#32851_ + 156 (__hidden#32877_:156)
2  PayPalCheckout                 0x2246b4 _hidden#3086_ + 4376544948 (__hidden#4373_:4376544948)
3  PayPalCheckout                 0x228e80 _hidden#2365_ + 4376563328 (__hidden#1342_:4376563328)
4  PayPalCheckout                 0x287258 _hidden#37557_ + 65 (__hidden#37599_:65)
5  PayPalCheckout                 0x288340 _hidden#26203_ + 121 (__hidden#1342_:121)
6  PayPalCheckout                 0x1bd438 _hidden#26189_ + 4376122424 (__hidden#26220_:4376122424)
7  PayPalCheckout                 0x10a280 _hidden#12702_ + 56 (__hidden#12739_:56)
8  PayPalCheckout                 0x25ded0 _hidden#35415_ + 156 (__hidden#1588_:156)
9  PayPalCheckout                 0x269d34 _hidden#35557_ + 4376829236 (__hidden#1342_:4376829236)
10 PayPalCheckout                 0x25e040 _hidden#35418_ + 4376780864
11 PayPalCheckout                 0x26b10c _hidden#35570_ + 4376834316
12 PayPalCheckout                 0x10a45c _hidden#12703_ + 61 (__hidden#12739_:61)
13 PayPalCheckout                 0x1be404 _hidden#26194_ + 161 (__hidden#26220_:161)
14 PayPalCheckout                 0x257af0 _hidden#26195_ + 1400 (__hidden#35749_:1400)
15 PayPalCheckout                 0xf5a58 _hidden#11354_ + 122 (__hidden#7241_:122)
16 PayPalCheckout                 0xff7b0 _hidden#11474_ + 4375345072
17 PayPalCheckout                 0xf5180 _hidden#11351_ + 4375302528 (__hidden#1342_:4375302528)
18 FirebasePerformance            0x1b930 __InstrumentDataTaskWithRequestCompletionHandler_block_invoke_2 + 300 (FPRNSURLSessionInstrument.m:300)
19 FirebasePerformance            0x1b930 __InstrumentDataTaskWithRequestCompletionHandler_block_invoke_2 + 300 (FPRNSURLSessionInstrument.m:300)
20 CFNetwork                      0x22178 CFURLRequestSetMainDocumentURL + 3028
21 CFNetwork                      0x33120 _CFNetworkErrorCopyLocalizedDescriptionWithHostname + 11444
22 libdispatch.dylib              0x2924 _dispatch_call_block_and_release + 32
23 libdispatch.dylib              0x4670 _dispatch_client_callout + 20
24 libdispatch.dylib              0xbdf4 _dispatch_lane_serial_drain + 672
25 libdispatch.dylib              0xc99c _dispatch_lane_invoke + 444
26 libdispatch.dylib              0x171b8 _dispatch_workloop_worker_thread + 656
27 libsystem_pthread.dylib        0x10f4 _pthread_wqthread + 288
28 libsystem_pthread.dylib        0xe94 start_wqthread + 8

### 🤔 Expected Behavior
- 

### 🌍 Environment

- iOS version: 15.3.1, 15.2.1 so far
- SDK version (`Checkout.version`):  0.88

### ➕ Additional Context
-

**Comment by jonathajones** [comment]
Hi @alihanaktay -
Thanks for the bug report. Some things to help us triage: 

1. Do you have any analytics of user behavior before the crashes? Do you have any user tokens that you could share to help us investigate?
2. How many crashes are you seeing with this trace?
3. Does this only occur on version 0.88.0, based on your analytics? 

Thank you!

**Comment by alihanaktay** [comment]
Hello @jonathajones ,

1. Unfortunately we don't have any user tokens. When I check the analytics there is no typical user behavior, I only see that users start the SDK after that crash happens.
2. Currently we are seeing that 3 crashes with 3 users we can say it is a rare case. Also when we check our system the users who faced crash, can buy via PayPal on their second try so we can probably say that, it is not always happen.
3. Yes this crash starts with 0.88.0.

Thank you!

**Comment by jonathajones** [comment]
Thanks for the follow up! A few more questions.
1. Our SDK does not use `FirebasePerformance` (or any Firebase framework). Did you happen to update the version of that SDK at the same time that you started seeing these crashes? I'm not familiar with it - so not sure how that framework is using URLSessionDelegate and if that could cause problems with our SDK.
2. What version of our SDK were you using prior to updating to 0.88.0?

**Comment by alihanaktay** [comment]
Hello @jonathajones ,

1. We didn't update any of Firebase SDKs but in the near future we can update and monitor this crash again and update you.
2. Our old version was 0.81.0

**Comment by jonathajones** [comment]
Thanks @alihanaktay - we're working on including debug symbols in the binary releases to better diagnose stack trace issues. I'll let you know here when we have a release that includes the dSyms. 

Thanks!
Jon

**Comment by jonathajones** [comment]
Hi @alihanaktay  - As of the latest release (0.94.0), we are now keeping and storing the dSYM files internally. 

When you have crash reports in the future that have a `_hidden` trace (and are on version 0.94.0), you would send us either the full crash report, or the raw trace with the desymbolicated memory addresses. We can then symbolicate the stack on our end and better investigate the cause.
